# Surrogacy Case Audit
Shows every file counted in the monthly statistics, one row per case.
Run all cells top-to-bottom, then use the filter cells at the bottom to inspect.

In [53]:


import os, re
from datetime import datetime
import pandas as pd

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_colwidth', 120)
pd.set_option('display.width', 300)

BASE_DIR = r"C:\Users\zhous\OneDrive - Tsong Law Group\Ralph Tsong's files - Active Cases\Surrogacy Cases"

In [54]:
# ── Core functions (kept in sync with surrogacy_monthly_final_v2.py) ──────────

# ── Agency canonical names & aliases ──────────────────────────────────────────
# Keys = lowercase variant seen in folder names; values = canonical display name.
# Add more rows here as needed — no other code needs to change.
AGENCY_CANONICAL = {
    # Giving Tree Surrogacy
    'gts':                                         'Giving Tree Surrogacy',
    'giving tree':                                 'Giving Tree Surrogacy',
    'giving tree surrogacy (review)':              'Giving Tree Surrogacy',

    # Royal Surrogacy & Egg Donation
    'royal surrogacy':                             'Royal Surrogacy & Egg Donation',
    'royal':                                       'Royal Surrogacy & Egg Donation',

    # Coast to Coast Surrogacy
    'coast to coast':                              'Coast to Coast Surrogacy',

    # Patriot Conceptions  ← note: do not mention agency name to client
    'patriot conceptions (do not mention agency)': 'Patriot Conceptions',
    'patriot':                                     'Patriot Conceptions',

    # LAS / Los Angeles Surrogacy
    'los angeles surrogacy':                       'LAS',
    'la surrogacy':                                'LAS',

    # All Families Surrogacy
    'all families':                                'All Families Surrogacy',
    'all family surrogacy':                        'All Families Surrogacy',
    'afs':                                         'All Families Surrogacy',

    # Blossom California Fertility
    'blossom california':                          'Blossom California Fertility',
    'blossom':                                     'Blossom California Fertility',

    # California Surrogacy Partners
    'csp':                                         'California Surrogacy Partners',

    # Simple Surrogacy
    'simple':                                      'Simple Surrogacy',

    # Oneworld Generations
    'oneworld generations surrogacy':              'Oneworld Generations',
    'oneworld':                                    'Oneworld Generations',

    # Modern Baby Family
    'modern baby family corp':                     'Modern Baby Family',
    'modern baby family':                          'Modern Baby Family',

    # Lily Baby Surrogacy
    'lily baby surrogacy':                         'Lily Baby',

    # SurrogateFirst
    'surrogatefirst':                              'SurrogateFirst',

    # Surrogacy4All
    'surrogacy4all':                               'Surrogacy4All',

    # Global Fertility
    'global fertility':                            'Global Fertility',

    # Dream Surrogacy
    'dream surrogacy':                             'Dream Surrogacy',

    # Blissful Bloom
    'blissful bloom':                              'Blissful Bloom',

    # ACRC
    'acrc':                                        'ACRC',

    # EDSI
    'edsi':                                        'EDSI',

    # Indy (independent / no agency)
    'indy':                                        'Indy',

    # Newgen Families
    'newgen families':                             'Newgen Families',
    'new gen families':                            'Newgen Families',
    'new gen':                                     'Newgen Families',
    'newgen':                                      'Newgen Families',
    'new generation families':                     'Newgen Families',
    'new generation':                              'Newgen Families',
}

# Special notes attached to canonical agency names (shown in exports)
AGENCY_NOTES = {
    'Patriot Conceptions': 'Do not mention agency name to client',
}


def canonicalize_agency(name):
    if not name:
        return name
    key = name.strip().lower()
    if key in AGENCY_CANONICAL:
        return AGENCY_CANONICAL[key]
    for variant, canonical in AGENCY_CANONICAL.items():
        if key == variant or key.startswith(variant + ' ') or variant.startswith(key + ' '):
            return canonical
    return name


def normalize_agency_name(agency_name):
    if "(do not use)" in agency_name.lower():
        return None
    normalized = re.sub(r'^review\s+', '', agency_name, flags=re.IGNORECASE)
    normalized = re.sub(r'^\s*\([A-Z]{2}\)\s*', '', normalized)
    normalized = re.sub(r'^-\s*', '', normalized)
    normalized = re.sub(r'\s*\([A-Z]{2}\)\s*$', '', normalized)
    normalized = re.sub(r',?\s*(Inc\.?|LLC|PLLC|Corp\.?|Ltd\.?)\s*$', '', normalized, flags=re.IGNORECASE)
    words = normalized.split()
    if len(words) >= 3 and words[-1].lower() in ['surrogacy', 'donation']:
        normalized = ' '.join(words[:-1])
    elif len(words) >= 2 and words[-1].lower() in ['nmc', 'break', 'review']:
        normalized = ' '.join(words[:-1])
    normalized = re.sub(r'\s+(Consulting|will change|for|do not)\s+.*$', '', normalized, flags=re.IGNORECASE)
    normalized = ' '.join(normalized.split()).strip()
    if not normalized:
        return None
    # reject bare 2-letter state codes (e.g. "WA", "CA") leaking through as agency names
    if re.match(r'^[A-Z]{2}$', normalized):
        return None
    return canonicalize_agency(normalized)


def parse_folder_name(folder_name):
    if not (folder_name.startswith('24-') or folder_name.startswith('25-') or folder_name.startswith('26-')):
        return None
    is_review = "review" in folder_name.lower()
    clean_name = re.sub(r'\s*-\s*(TERMINATE4D|TERMINATED)\s*$', '', folder_name, flags=re.IGNORECASE).strip()
    name_part = re.sub(r'^2[456]-\S+\s+', '', clean_name, flags=re.IGNORECASE).strip()
    agency = None
    parts = [p.strip() for p in clean_name.split(' - ')]
    if len(parts) >= 2:
        agency = parts[-1]
    if not agency:
        norm = re.sub(r'\s*[–—]\s*', ' - ', name_part)
        norm = re.sub(r'(?<!\s)-\s+', ' - ', norm)
        norm = re.sub(r'\s+-([^\s-])', r' - \1', norm)
        parts = [p.strip() for p in norm.split(' - ')]
        if len(parts) >= 2:
            agency = parts[-1]
    if not agency and is_review:
        m = re.search(r'\breview\s+([^\s].+?)\s*$', name_part, re.IGNORECASE)
        if m:
            agency = m.group(1).strip()
    if not agency and '&' in name_part:
        after_amp = name_part.split('&')[-1].strip()
        after_amp = re.sub(r'\s*\([A-Z]{2,3}(?:-[A-Z]{2,3})?\)\s*', ' ', after_amp).strip()
        after_amp = re.sub(r'\s*\b(PBO|nmc|review|clean\s+up)\s*$', '', after_amp, flags=re.IGNORECASE).strip()
        after_amp = re.sub(r'^(\w[\w\-]+(?:\s+and\s+\w[\w\-]+)?)\s+', '', after_amp).strip()
        after_amp = re.sub(r'\s*\b(PBO|nmc|review)\s*$', '', after_amp, flags=re.IGNORECASE).strip()
        if after_amp:
            agency = after_amp
    if agency:
        agency = agency.strip()
        if agency.upper() not in ['XX', 'XXX', 'XXXX']:
            return (agency, is_review)
    return None


def find_agreement_file(folder_path):
    try:
        for entry in os.scandir(folder_path):
            if not entry.is_file():
                continue
            n = entry.name.lower()
            if any(n.endswith(ext) for ext in ['.pdf', '.jpg', '.jpeg', '.png', '.gif', '.tiff', '.bmp']):
                if 'agreement' in n and 'legal' in n and 'representation' in n and 'signed' in n:
                    return entry
    except:
        pass
    return None


def find_clearance_letter(folder_path):
    try:
        for entry in os.scandir(folder_path):
            if not entry.is_file():
                continue
            n = entry.name.lower()
            if 'clearance' in n and any(n.endswith(e) for e in ['.pdf', '.jpg', '.jpeg', '.png', '.gif', '.tiff', '.bmp']):
                return entry
    except:
        pass
    return None

print('Functions loaded OK')
print(f'Agency aliases: {len(AGENCY_CANONICAL)}  |  Agency notes: {len(AGENCY_NOTES)}')

Functions loaded OK
Agency aliases: 36  |  Agency notes: 1

In [55]:
# ── Scan and collect one record per counted case ───────────────────────────────

_SKIP_PATTERN = re.compile(
    r'\b(TERMINATE4D|TERMINATED|NOT\s+DRAFTED\s+YET|DECIDE\s+NOT\s+TO\s+REPRESENT|DECLINED)\b',
    re.IGNORECASE
)

records = []

for folder_name in sorted(os.listdir(BASE_DIR)):
    if folder_name.startswith('.') or folder_name.startswith('~'):
        continue
    folder_path = os.path.join(BASE_DIR, folder_name)
    if not os.path.isdir(folder_path):
        continue

    # skip terminated / irrelevant cases entirely
    if _SKIP_PATTERN.search(folder_name):
        continue

    parsed = parse_folder_name(folder_name)
    if not parsed:
        continue

    raw_agency, is_review = parsed
    agency = normalize_agency_name(raw_agency)
    if not agency:
        continue

    entry = find_agreement_file(folder_path)
    source = 'signed agreement'
    if not entry:
        entry = find_clearance_letter(folder_path)
        source = 'legal clearance letter'
    if not entry:
        continue

    try:
        mtime = entry.stat().st_mtime
        agreement_date = datetime.fromtimestamp(mtime)
    except:
        continue

    records.append({
        'month':          agreement_date.strftime('%Y-%m'),
        'date':           agreement_date.strftime('%Y-%m-%d'),
        'agency':         agency,
        'status':         'review' if is_review else 'drafting',
        'case_folder':    folder_name,
        'agreement_file': entry.name,
        'source':         source,
        'path_len':       len(entry.path),
    })

df = pd.DataFrame(records).sort_values(['month', 'agency', 'date']).reset_index(drop=True)
print(f'Total cases counted: {len(df)}')
print(f'  via signed agreement:       {(df["source"]=="signed agreement").sum()}')
print(f'  via legal clearance letter: {(df["source"]=="legal clearance letter").sum()}')
print(f'Months covered:      {df["month"].nunique()}  ({df["month"].min()} → {df["month"].max()})')
print(f'Agencies found:      {df["agency"].nunique()}')
print(f'Drafting:            {(df["status"]=="drafting").sum()}')
print(f'Review:              {(df["status"]=="review").sum()}')

Total cases counted: 1090
  via signed agreement:       1004
  via legal clearance letter: 86
Months covered:      30  (2024-01 → 2026-06)
Agencies found:      183
Drafting:            769
Review:              321

## Full listing — every counted case

In [56]:
df[['month', 'date', 'agency', 'status', 'case_folder', 'agreement_file']]

        month        date                         agency    status                                                                case_folder                                                                                                 agreement_file
0     2024-01  2024-01-20                           ACRC  drafting                                  24-S-09 Wang and Jiang & Haug (MN) - ACRC                            (Signed) Agreement for Legal Representation - MN - Wang and Jiang & Haug - ACRC.pdf
1     2024-01  2024-01-11         All Families Surrogacy    review  24-S-05 Santelli and Hagood & Severn - Review (WA) All Families Surrogacy                 Agreement for Legal Representation - Santelli and Hagood & Severn review (WA) AFS - signed.pdf
2     2024-01  2024-01-22  California Surrogacy Partners    review                        24-S-08 Latner and Feldstein & Freytag - Review CSP             Agreement for Legal Representation - Latner and Feldstein & Freytag - Review - CSP - IM Signed.pdf
3     2024-01  2024-01-08          Giving Tree Surrogacy    review                   24-S-03 Ding & Martinez - Giving Tree Surrogacy (Review)                                           Agreement for Legal Representation- Martinez GTS review - signed.pdf
4     2024-01  2024-01-18          Giving Tree Surrogacy    review                    24-S-07 Watters and Mastrodonato & Carli - Review - GTS              Agreement for Legal Representation - Watters and Mastrodonato & Carli - Review - GTS - signed.pdf
...       ...         ...                            ...       ...                                                                        ...                                                                                                            ...
1085  2026-06  2026-06-10                    One Village  drafting                          26-S-283 Hung & Ward (KY) - One Village Surrogacy                  请签署Agreement for Legal Representation - Hung & Ward (KY) - One Village Surrogacy - signed.pdf
1086  2026-06  2026-06-05           Oneworld Generations  drafting             26-S-279 Zhang and Wu & Brown - Oneworld Generations Surrogacy  请签署 - Agreement for Legal Representation - Zhang and Wu & Brown - Oneworld Generations Surrogacy - signed.pdf
1087  2026-06  2026-06-02                  Surrogacy4All    review                26-S-273 Dean and Mangla & Good (OK) - Surrogacy4All review           Agreement for Legal Representation - Dean and Mangla & Good (OK) - Surrogacy4All review - signed.pdf
1088  2026-06  2026-06-05                 SurrogateFirst  drafting                     26-S-265 Xiao and Mi & Simbe (UT) - SurrogateFirst NMC                    Agreement for Legal Representation - Xiao and Mi & Simbe (UT) - SurrogateFirst - signed.pdf
1089  2026-06  2026-06-10        The Fertility Solutions  drafting             26-S-282 Ma and Fang & Tonkovich - The Fertility Solutions LLC        (Signed) Agreement for Legal Representation - Ma and Fang & Tonkovich - The Fertility Solutions LLC.pdf

[1090 rows x 6 columns]

## Monthly summary (pivot)

In [57]:
pivot_month = (
    df.groupby(['month', 'status'])
      .size()
      .unstack(fill_value=0)
      .reindex(columns=['drafting', 'review'], fill_value=0)
)
pivot_month['total'] = pivot_month.sum(axis=1)
pivot_month.loc['TOTAL'] = pivot_month.sum()
pivot_month

status   drafting  review  total
month
2024-01         6       6     12
2024-02        10       4     14
2024-03        15       7     22
2024-04         9      10     19
2024-05        13       3     16
2024-06        11       3     14
2024-07        18       6     24
2024-08        20       5     25
2024-09        19       8     27
2024-10        21      15     36
2024-11        28       7     35
2024-12        26       9     35
2025-01        29      13     42
2025-02        16       8     24
2025-03        36       5     41
2025-04        30       8     38
2025-05        22      11     33
2025-06        22      11     33
2025-07        37      14     51
2025-08        34      19     53
2025-09        32      19     51
2025-10        45      21     66
2025-11        35      14     49
2025-12        27      15     42
2026-01        41      18     59
2026-02        38      16     54
2026-03        49      19     68
2026-04        39      17     56
2026-05        30       6     36
2026-06        11       4     15
TOTAL         769     321   1090

## Agency summary (all months combined)

In [58]:
pivot_agency = (
    df.groupby(['agency', 'status'])
      .size()
      .unstack(fill_value=0)
      .reindex(columns=['drafting', 'review'], fill_value=0)
)
pivot_agency['total'] = pivot_agency.sum(axis=1)
pivot_agency.sort_values('total', ascending=False)

status                                                drafting  review  total
agency
LAS                                                        178      24    202
Blossom California Fertility                                24      65     89
SurrogateFirst                                              79       3     82
Giving Tree Surrogacy                                       38      21     59
Indy                                                        13      16     29
Twinkle Surrogacy                                           28       0     28
Flying Stork                                                23       0     23
C&T Fertility Consultant                                     2      20     22
Lily Baby                                                   21       0     21
Blissful Bloom                                              15       4     19
Ivy Baby                                                    18       0     18
EDSI                                                        18       0     18
Kindred Surrogacy                                           12       3     15
SAI                                                         15       0     15
Physician's Surrogacy                                        0      14     14
Babies Sprouts                                               0      14     14
Royal Surrogacy & Egg Donation                              11       2     13
Surrogacy.is                                                 5       8     13
Global Fertility                                            12       0     12
Stronger Together                                            9       1     10
Pitter Patter                                                7       3     10
ACRC                                                         9       1     10
Dreamweaver                                                  3       6      9
Carrying Hope                                                7       2      9
Loving Journey                                               9       0      9
LifeBridge Surrogacy                                         7       2      9
Full Bloom Surrogacy                                         0       8      8
Joy of Life                                                  8       0      8
GSHC                                                         8       0      8
Oneworld Generations                                         8       0      8
All Families Surrogacy                                       4       3      7
Oceanside                                                    6       1      7
Shining Light Baby                                           5       2      7
All Love                                                     5       1      6
FSC                                                          3       3      6
Reproductive Options                                         0       6      6
Newgen Families                                              0       6      6
Road to Baby                                                 5       0      5
Oceanside Surrogacy                                          2       3      5
Family Source Consultants                                    3       2      5
PBO                                                          2       3      5
New Life                                                     4       0      4
One Village                                                  4       0      4
Alcea                                                        2       2      4
Ivy Baby Surrogacy                                           0       4      4
Tiny Treasures Advocacy                                      4       0      4
Pacific Miracles                                             4       0      4
All Love Surrogacy                                           0       3      3
Ivy Surrogacy                                                3       0      3
New Life Surrogacy                                           0       3      3
Modern Baby Family                                           3       0      3
STS                                                          1       2      3
Carrying Dreams                                              3       0      3
Biggest Ask                                                  2       1      3
Family Makers                                                2       1      3
Golden Surrogacy                                             0       3      3
Your Fertility Advocate                                      2       1      3
Origo                                                        2       1      3
Second Chance                                                3       0      3
SLS                                                          3       0      3
Genesis Rising                                               3       0      3
Patriot Conceptions                                          2       0      2
surrogacy.is                                                 2       0      2
Smart Surrogacy                                              2       0      2
SoCal Surrogacy                                              2       0      2
Surrogate Prime                                              2       0      2
StrongerTogether                                             1       1      2
US Surrogacy                                                 2       0      2
independent                                                  1       1      2
Surrogacy4All                                                0       2      2
Roots Surrogacy                                              2       0      2
OFG & Stork                                                  0       2      2
Life Bridge Consulting                                       2       0      2
NWSC                                                         1       1      2
OFG                                                          0       2      2
Life Bridge                                                  2       0      2
International Family Agency                                  2       0      2
ISC                                                          2       0      2
Simple Surrogacy                                             0       2      2
Tiny Sprouts                                                 2       0      2
Genesis Group                                                2       0      2
Forever Blessed                                              2       0      2
I Baby                                                       2       0      2
Hellobaby Surrogacy                                          2       0      2
Gestacy                                                      1       1      2
Family Tree Surrogacy Center                                 2       0      2
Family Tree                                                  2       0      2
Coast to Coast Surrogacy                                     1       1      2
Central Coast                                                2       0      2
Dream Surrogacy                                              2       0      2
Delivering Hope                                              2       0      2
California Baby Consulting                                   2       0      2
California Surrogacy Partners                                0       2      2
Same Love                                                    2       0      2
4Y Life                                                      1       0      1
Dreamcourier (in fact Life Bridge Surrogacy)                 1       0      1
Dreams of Parenthood                                         1       0      1
BlissfulBloom (cc Alice not Mayara)                          1       0      1
C2 Surrogacy                                                 1       0      1
CA PBO                                                       1       0      1
Carrying Hope Surrogacy                                      0       1      1
Choices Donations                                            0       1      1
Compass Surrogacy                                            1       0      1
Accel Conceptions Egg Donation &                             1       0      1
Abundant Life                                                0       1      1
Abundant Beginnings Co                                       1       0      1
ALS                                                          0       1      1
AED                                                          1       0      1
Alcea Surrogacy                                              1       0      1
Angel Health                                                 0       1      1
American Surrogacy                                           1       0      1
Angel Health Medical Limited                                 0       1      1
Asian Family                                                 1       0      1
Babies Spouts                                                0       1      1
Babiology                                                    0       1      1
Babiology Surrogacy & Egg                                    1       0      1
Baby Boom                                                    1       0      1
Baby Sprouts                                                 0       1      1
Babytree Surrogacy                                           0       1      1
Family Matters                                               1       0      1
Family Creations                                             1       0      1
Family Choice Surrogacy                                      0       1      1
Fairfax Surrogacy                                            0       1      1
Expect Miracles                                              1       0      1
FTSC                                                         0       1      1
Egg Donation                                                 0       1      1
Elite IVF                                                    0       1      1
JSA                                                          1       0      1
New Match                                                    1       0      1
New Leaf Surrogacy                                           0       1      1
Morris                                                       1       0      1
Nascency Surrogacy                                           0       1      1
Mothers First                                                1       0      1
New Dawn                                                     1       0      1
Modern Family                                                1       0      1
HelloBaby Surrogacy                                          1       0      1
HelloBaby                                                    1       0      1
GS Moms                                                      1       0      1
Forever Families Surrogacy                                   0       1      1
Family Solutions International                               0       1      1
GSA Second Opinion                                           0       1      1
Family Solutions Int'l                                       1       0      1
Great Beginnings Surrogacy Services including escrow         1       0      1
Heart to Heart                                               1       0      1
Life Bridge Surrogacy                                        0       1      1
Lucky D                                                      1       0      1
Harvest Surrogacy                                            1       0      1
Great Beginnings Surrogacy including escrow                  1       0      1
IFA                                                          1       0      1
Integrative Surrogacy                                        1       0      1
International Family Agency, LLC                             0       1      1
OK Compliance                                                0       1      1
Shining Light Babies                                         1       0      1
SCS                                                          1       0      1
Same Love Surrogacy                                          0       1      1
Reproductive options                                         0       1      1
Ramirez                                                      1       0      1
Precious Gifts                                               1       0      1
SAI PBO                                                      0       1      1
Pacific Surrogacy & Egg                                      1       0      1
Origo Surrogacy                                              1       0      1
Pineapple Surrogacy                                          0       1      1
Physicians Surrogacy                                         0       1      1
Pinnacle Surrogacy                                           1       0      1
Pinnacle Surrogacy review (withdrawn)                        0       1      1
PrimeSurro                                                   1       0      1
Opal Surrogacy Services                                      1       0      1
Surrogacy.is PBO                                             1       0      1
Surroconnections                                             1       0      1
Surrogacy Partnership                                        0       1      1
Surrogacy by Faith                                           1       0      1
Surro Connections PBO                                        0       1      1
Shining Light Baby (IN-WA)                                   1       0      1
Sister Family                                                1       0      1
StrongerTogether review NV                                   0       1      1
WFI                                                          0       1      1
The Fertility Solutions                                      1       0      1
Surrogate Steps                                              0       1      1
West Coast Surrogacy                                         0       1      1
XYEdge Consultants                                           1       0      1
Western Fertility Institute                                  0       1      1
surroconnections                                             0       1      1
the biggest ask                                              0       1      1

## Agency × Month breakdown

In [59]:
pivot_full = (
    df.groupby(['agency', 'month'])
      .size()
      .unstack(fill_value=0)
)
pivot_full['TOTAL'] = pivot_full.sum(axis=1)
pivot_full.sort_values('TOTAL', ascending=False)

month                                                 2024-01  2024-02  2024-03  2024-04  2024-05  2024-06  2024-07  2024-08  2024-09  2024-10  ...  2025-10  2025-11  2025-12  2026-01  2026-02  2026-03  2026-04  2026-05  2026-06  TOTAL
agency                                                                                                                                          ...
LAS                                                         1        5        2        4        1        2        6       10        5       11  ...        8        3        7       11       13       12        7        7        3    202
Blossom California Fertility                                0        0        0        0        0        0        0        0        1        2  ...       12        3        3        8        4        5        5        3        0     89
SurrogateFirst                                              2        1        2        1        3        1        3        1        1        3  ...        3        5        4        3        2        3        6        1        1     82
Giving Tree Surrogacy                                       2        1        1        5        1        1        1        2        0        1  ...        1        3        1        1        4        5        5        2        0     59
Indy                                                        0        0        2        1        1        0        0        1        2        1  ...        0        0        1        0        3        2        1        1        0     29
Twinkle Surrogacy                                           0        0        0        0        0        0        1        0        0        0  ...        2        6        2        1        2        0        2        1        0     28
Flying Stork                                                0        1        1        0        1        0        0        1        1        0  ...        0        1        0        0        0        1        1        2        0     23
C&T Fertility Consultant                                    0        0        0        0        0        0        0        0        0        1  ...        1        2        3        5        0        1        1        1        0     22
Lily Baby                                                   0        0        0        0        0        0        0        0        0        0  ...        1        3        1        2        1        3        2        0        0     21
Blissful Bloom                                              0        0        0        0        0        3        1        0        1        0  ...        0        0        2        1        0        1        0        0        1     19
Ivy Baby                                                    0        0        0        0        0        1        1        4        4        1  ...        0        0        0        0        0        0        0        0        0     18
EDSI                                                        0        0        0        0        0        0        0        0        0        0  ...        5        1        1        1        1        1        1        0        2     18
Kindred Surrogacy                                           2        1        0        0        1        0        0        0        0        0  ...        0        1        0        0        0        0        1        0        0     15
SAI                                                         0        0        0        0        0        0        0        0        0        0  ...        6        1        2        1        1        1        0        0        0     15
Physician's Surrogacy                                       0        0        0        0        0        0        0        0        0        0  ...        1        2        3        0        0        0        0        0        0     14
Babies Sprouts                                              0        0        0        0        0        0        0        0        0        1  ...        0        0        0        1        4        3        1        1        0     14
Royal Surrogacy & Egg Donation                              0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        1        0        1        0     13
Surrogacy.is                                                0        1        0        0        1        0        2        0        0        0  ...        1        1        0        0        0        3        1        1        0     13
Global Fertility                                            0        0        0        0        0        0        0        0        0        0  ...        1        0        0        1        0        1        1        1        1     12
Stronger Together                                           0        0        0        0        0        0        0        0        1        2  ...        0        0        0        0        0        0        0        0        0     10
Pitter Patter                                               2        0        0        0        0        0        0        0        3        0  ...        1        0        0        1        0        0        0        0        0     10
ACRC                                                        1        1        0        0        1        1        0        0        0        0  ...        1        1        0        0        0        2        0        1        0     10
Dreamweaver                                                 0        1        0        0        0        0        0        0        1        0  ...        1        1        0        0        0        1        0        0        1      9
Carrying Hope                                               0        0        1        0        0        0        0        1        0        0  ...        0        0        0        1        0        0        0        0        0      9
Loving Journey                                              0        0        0        0        0        0        0        0        0        0  ...        2        0        0        0        1        1        0        1        0      9
LifeBridge Surrogacy                                        0        0        0        0        0        0        0        0        0        0  ...        0        1        1        3        2        2        0        0        0      9
Full Bloom Surrogacy                                        0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        2        3        3        0        0      8
Joy of Life                                                 0        0        0        0        0        0        0        0        0        0  ...        1        0        1        0        0        0        1        1        0      8
GSHC                                                        0        0        0        0        0        0        0        0        0        1  ...        0        0        1        0        0        0        2        0        0      8
Oneworld Generations                                        0        0        0        0        0        0        0        0        1        0  ...        1        1        0        0        0        1        1        0        1      8
All Families Surrogacy                                      1        0        0        0        0        0        0        0        0        0  ...        2        0        0        0        0        0        0        0        0      7
Oceanside                                                   0        0        1        0        1        0        0        0        1        1  ...        0        0        0        0        1        0        0        0        0      7
Shining Light Baby                                          0        0        0        0        0        0        0        0        1        0  ...        0        0        0        1        1        0        2        1        0      7
All Love                                                    0        0        0        1        0        0        1        0        0        1  ...        0        0        0        0        0        0        1        0        0      6
FSC                                                         0        0        0        1        0        0        0        0        1        0  ...        0        1        1        0        0        0        0        0        0      6
Reproductive Options                                        0        0        0        0        0        1        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      6
Newgen Families                                             0        0        0        0        0        0        0        1        0        0  ...        2        0        0        0        1        0        1        0        0      6
Road to Baby                                                0        0        0        0        0        0        0        0        1        0  ...        0        0        0        0        0        0        0        0        0      5
Oceanside Surrogacy                                         0        0        0        0        0        0        0        0        0        1  ...        1        0        2        0        0        0        0        0        0      5
Family Source Consultants                                   0        0        0        0        0        0        0        0        1        0  ...        2        0        0        0        0        0        0        0        0      5
PBO                                                         0        0        0        0        1        0        0        0        0        0  ...        0        0        0        2        0        0        0        0        0      5
New Life                                                    0        0        0        0        0        0        1        0        0        0  ...        0        0        0        0        0        0        0        0        0      4
One Village                                                 0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        1        0        0        1        1      4
Alcea                                                       0        0        0        0        1        0        1        0        0        0  ...        1        0        0        0        0        0        0        0        0      4
Ivy Baby Surrogacy                                          0        0        0        0        0        0        0        0        0        3  ...        0        0        0        0        0        0        0        0        0      4
Tiny Treasures Advocacy                                     0        0        0        0        0        0        0        0        0        0  ...        0        1        0        0        0        0        0        1        0      4
Pacific Miracles                                            0        0        0        0        0        0        1        0        1        0  ...        0        0        0        0        0        0        0        0        0      4
All Love Surrogacy                                          0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        1        0        1        0        0      3
Ivy Surrogacy                                               0        0        1        0        0        0        0        0        0        0  ...        0        0        0        0        0        1        0        0        0      3
New Life Surrogacy                                          0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      3
Modern Baby Family                                          0        0        0        0        0        0        0        0        0        0  ...        1        0        0        0        0        0        1        0        1      3
STS                                                         0        0        0        0        0        0        0        0        0        0  ...        0        0        0        1        0        0        0        1        0      3
Carrying Dreams                                             0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        1        0        0        0      3
Biggest Ask                                                 0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      3
Family Makers                                               0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      3
Golden Surrogacy                                            0        0        0        0        0        0        0        0        0        0  ...        0        0        2        0        0        0        0        0        0      3
Your Fertility Advocate                                     0        0        0        0        0        0        0        0        0        0  ...        0        0        0        2        0        0        0        0        0      3
Origo                                                       0        0        1        0        0        0        0        0        0        0  ...        0        0        0        0        0        1        0        0        0      3
Second Chance                                               0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        1        1        0        1        0      3
SLS                                                         0        0        1        0        0        0        0        0        0        0  ...        0        0        0        0        0        1        0        0        0      3
Genesis Rising                                              0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        1        0        0      3
Patriot Conceptions                                         0        0        0        0        0        0        0        0        0        0  ...        1        0        1        0        0        0        0        0        0      2
surrogacy.is                                                0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
Smart Surrogacy                                             0        0        1        0        0        1        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
SoCal Surrogacy                                             0        0        0        0        0        0        0        0        0        0  ...        1        0        0        0        0        0        0        0        0      2
Surrogate Prime                                             0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
StrongerTogether                                            0        0        0        1        0        0        0        0        0        1  ...        0        0        0        0        0        0        0        0        0      2
US Surrogacy                                                0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
independent                                                 0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        2        0        0        0      2
Surrogacy4All                                               0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        1      2
Roots Surrogacy                                             0        0        0        0        0        0        0        0        0        1  ...        0        0        0        0        0        0        0        0        0      2
OFG & Stork                                                 0        0        1        0        0        0        0        0        0        0  ...        0        0        0        1        0        0        0        0        0      2
Life Bridge Consulting                                      0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        2        0      2
NWSC                                                        0        0        0        0        0        0        0        0        0        0  ...        0        1        0        0        0        0        0        0        0      2
OFG                                                         0        0        1        0        0        1        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
Life Bridge                                                 0        0        0        0        0        0        0        0        0        0  ...        0        0        0        1        0        1        0        0        0      2
International Family Agency                                 0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
ISC                                                         0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        1        1        0        0        0      2
Simple Surrogacy                                            0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        2        0        0        0        0      2
Tiny Sprouts                                                0        0        0        0        0        0        0        0        0        0  ...        0        0        1        1        0        0        0        0        0      2
Genesis Group                                               0        0        0        0        0        0        1        0        0        0  ...        1        0        0        0        0        0        0        0        0      2
Forever Blessed                                             0        0        1        0        0        1        0        0        0        0  ...        0        0        0        0        0        0        0        0        0      2
I Baby                                                      0        0        0        0        0        0        0        0        0        0  ...        0        0        0        0        0        0        0        1        0      2

---
## Filter helpers — change the values below and re-run the cell

In [60]:
# ── Filter by month ───────────────────────────────────────────────────────────
MONTH = '2025-01'   # ← change to any YYYY-MM

filtered = df[df['month'] == MONTH][['date', 'agency', 'status', 'case_folder', 'agreement_file']]
print(f'{MONTH}: {len(filtered)} cases  '
      f'(drafting={( filtered["status"]=="drafting").sum()}, '
      f'review={(filtered["status"]=="review").sum()})')
filtered

2025-01: 42 cases  (drafting=29, review=13)

           date                        agency    status                                                                          case_folder                                                                                                           agreement_file
279  2025-01-09                      All Love  drafting                                   25-S-11 Mao & Villanueva (WA) - All Love Surrogacy                             (Signed) Agreement for Legal Representation - Mao & Villanueva (WA) - All Love Surrogacy.pdf
280  2025-01-07                Babies Sprouts    review                                 25-S-13 Zhou and Zhu & Gamez - Babies Sprouts review                           (Signed) Agreement for Legal Representation - Zhou and Zhu & Gamez - Babies Sprouts review.pdf
281  2025-01-22                   Biggest Ask    review                                    24-S-319 Hernandez and Osuna - Biggest Ask review                                      Agreement for Legal Representation - Hernandez and Osuna - Biggest Ask - signed.pdf
282  2025-01-07                Blissful Bloom  drafting                                         24-S-309 Chen & Record (NJ) - Blissful Bloom                                    Agreement for Legal Representation - Chen & Record (NJ) - Blissful Bloom - signed.pdf
283  2025-01-05  Blossom California Fertility    review             24-S-318 Wang and Li & Gagnon (AZ) - Blossom California Fertility review        (Signed) Agreement for Legal Representation - Wang and Li & Gagnon (AZ) - Blossom California Fertility review.pdf
284  2025-01-15  Blossom California Fertility    review              25-S-18 Xu and Cao & Naranjo (WA) - Blossom California Fertility review  Agreement for Legal Representation- Xu and Cao & Naranjo (WA) - Blossom California Fertility review 01142025 - signe...
285  2025-01-21  Blossom California Fertility    review              25-S-25 Chen and Xu & Lina Ospina - Blossom California Fertility review           Agreement for Legal Representation - Chen and Xu & Gildardo - Blossom California Fertility review - signed.pdf
286  2025-01-22  Blossom California Fertility    review       25-S-27 Huang and Huang & Mercado-Flores - Blossom California Fertility review  Please Sign - Agreement for Legal Representation - Huang and Huang & Mercado-Flores - Blossom California review - si...
287  2025-01-22  Blossom California Fertility  drafting                              25-S-33 Xu & Gloria (TX) - Blossom California Fertility                    (signed) Agreement for Legal Representation - Xu & Gloria (TX) - Blossom California Fertility (2).pdf
288  2025-01-22               Carrying Dreams  drafting                        25-S-20 Lugten and Bouter & Greytak (WA-AZ) - Carrying Dreams                  Agreement for Legal Representation - Lugten and Bouter & Greytak (AZ-WA) - Carrying Dreams - signed.pdf
289  2025-01-30                 Carrying Hope    review                        25-S-39 Thurston & Wooley-Bernard (AZ) - Carrying Hope review                  Agreement for Legal Representation - Thurston & Wooley-Bernard (AZ) - Carrying Hope review - signed.pdf
290  2025-01-14               Delivering Hope  drafting                              25-S-17 Chen and Zhang & Barajas (NV) - Delivering Hope                        (Signed) Agreement for Legal Representation - Chen and Zhang & Barajas (NV) - Delivering Hope.pdf
291  2025-01-23               Delivering Hope  drafting                                    25-S-34 Lai and Xie & Anthenien - Delivering Hope                             Agreement for Legal Representation -  Lai and Xie & Anthenien - Delivering Hope - signed.pdf
292  2025-01-02               Dream Surrogacy  drafting                                           24-S-317 Moore & Mounsey - Dream Surrogacy                                                        Agreement for Legal Representation - Moore & Mounsey - signed.pdf
293  2025-01-27             Fairfax Surrogacy    review                            25-S-21 Marrero and Mejia (AZ) - Fairfax Surrogacy review                                                                     (Both Signed) Agreement for Legal Representation.pdf
294  2025-01-06     Family Source Consultants  drafting                                  25-S-02 Ma & Floro (IL) - Family Source Consultants                         请签署Agreement for Legal Representation - Ma & Floro (IL) - Family Source Consultants - signed.pdf
295  2025-01-13     Family Source Consultants  drafting         25-S-16 Palmero and McNally & Parson (NC-IL law) - Family Source Consultants                                  Agreement for Legal Representation  - Palmero and McNally & Parson (NC-IL) - signed.pdf
296  2025-01-03         Giving Tree Surrogacy    review                                               25-S-06 Yi and Jin & Vaca - GTS Review                                          Agreement for Legal Representation - Yi and Jin & Vaca- GTS Review - signed.pdf
297  2025-01-07         Giving Tree Surrogacy  drafting                                                     25-S-10 Liu & Stoufer (AR) - GTS                                            请签署Agreement for Legal Representation - Liu & Stoufer (AR) - GTS - signed.pdf
298  2025-01-11         Giving Tree Surrogacy  drafting                                                     25-S-07 Xie & Stevens (OK) - GTS                                               (Signed) Agreement for Legal Representation - Xie & Stevens (OK) - GTS.pdf
299  2025-01-03                          Indy    review                               25-S-05 Verst and Smith & Lukenbach (WA) - Indy review                               Agreement for Legal Representation- Verst and Smith & Lukenbach - Indy review - signed.pdf
300  2025-01-23                          Indy  drafting                                                25-S-31 Mi and Au & Lara - indy & FSC                                           Agreement for Legal Representation - Mi and Au & Lara and Mireles - signed.pdf
301  2025-01-21                      Ivy Baby  drafting                                    25-S-32 Shao & Connolly (AZ) - Ivy Baby Surrogacy                              (Signed) Agreement for Legal Representation - Shao & Connolly (AZ) - Ivy Baby Surrogacy.pdf
302  2025-01-11                   Joy of Life  drafting                                             25-S-15 Xu and Wang & Luis - Joy of Life                                       (Signed) Agreement for Legal Representation - Xu and Wang & Luis - Joy of Life.pdf
303  2025-01-02                           LAS  drafting                         25-S-04 Ran Xu and Bo Zhao & Ana Laura Aviles Castillo - LAS                   (Signed) Agreement for Legal Representation - Ran Xu and Bo Zhao & Ana Laura Aviles Castillo - LAS.pdf
304  2025-01-04                           LAS  drafting                                          25-S-03 Yanyou Chen & Ashley Carrillo - LAS                                 请签署Agreement for Legal Representation - Yanyou Chen & Ashley Carrillo - LAS - signed.pdf
305  2025-01-09                           LAS  drafting            25-S-14 Haoxue Zhu and Yifeng Cao & Jennifer Marisol Rivera Quntero - LAS              (Signed) Agreement for Legal Representation - Haoxue Zhu and Yifeng Cao & Jennifer Rivera Quntero - LAS.pdf
306  2025-01-15                           LAS  drafting  24-S-312 Mayumi Nishiyama and Kentaro Abe & Adriana Flores and James Robinett - LAS                                                                                     legal clearance letter  Adriana .pdf
307  2025-01-16                           LAS  drafting                     25-S-19 Xiaojun Zhu and Hongzhan Li & Ebelin Oropeza Perez - LAS          (signed) Agreement for Legal Representation -  Xiaojun Zhu and Hongzhan Li & Ebelin Oropeza Perez - LAS (2).pdf
308  2025-01-20                           LAS    review                                     25-S-23 Jing Yang & Marisol Sliakis - LAS review                              (Signed) Agreement for Legal Representation -  Jing Yang & Marisol Sliakis - LAS review.pdf
309  2025-01-21                           LAS  drafting                        25-S-30 Yuan-Hsin Chang and Jia-Lin Liu & Diana Arteaga - LAS                 (Signed) Agreement for Legal Representation -  Yuan-Hsin Chang and Jia-Lin Liu & Diana Arteaga - LAS.pdf
310  2025-01-23                           LAS  drafting                              25-S-35 Yifan Ren and Bingchen Chen & Lizet Bravo - LAS                       (Signed) Agreement for Legal Representation - Yifan Ren and Bingchen Chen & Lizbet Bravo - LAS.pdf
311  2025-01-27                           LAS    review              25-S-24 Christine Bohm and Friedrich Bohm & Lauren Bashara - LAS review                              Full Legal Clearance Letter -  Christine Bohm and Friedrich Bohm & Lauren Bashara - LAS.pdf
312  2025-01-29                           LAS  drafting                       25-S-29 Maria Ito and Takahiro Ito & Rubi Julia Balderas - LAS                (Signed) Agreement for Legal Representation -  Maria Ito and Takahiro Ito & Rubi Julia Balderas - LAS.pdf
313  2025-01-26                Loving Journey  drafting                   25-S-28 Peter Brandon Wee Lu-Xian & Callison (GA) - Loving Journey  Please Sign - Agreement for Legal Representation - Peter Brandon Wee Lu-Xian & Callison (GA) - Loving Journey - sign...
314  2025-01-29                Loving Journey  drafting                                 25-S-37 Hua and Zuo & Atchison (KY) - Loving Journey                           (Signed) Agreement for Legal Representation - Hua and Zuo & Atchison (KY) - Loving Journey.pdf
315  2025-01-03                 Pitter Patter  drafting                                           25-S-01 Sampat & Bird (NV) - Pitter Patter                                       Agreement for Legal Representation - Sampat & Bird (NV) - Pitter Patter signed.pdf
316  2025-01-09                       SAI PBO    review                                         25-S-08 Ouyang & Downs (WA) - SAI PBO Review                                       Agreement for Legal Representation- Ouyang & Downs (WA) SAI PBO Review signed .pdf
317  2025-01-04             Stronger Together  drafting                                25-S-09 Xiao and Wang & Covington - Stronger Together                          (Signed) Agreement for Legal Representation - Xiao and Wang & Covington - Stronger Together.pdf
318  2025-01-02               Surrogate Prime  drafting                                 24-S-278 Lin and Luo & Morgan (GA) - Surrogate Prime                                                                                         GC Legal Clearance Z. Morgan.pdf
319  2025-01-20                SurrogateFirst  drafting                            24-S-246 Chen and Feng & Schuerfeld (TX) - SurrogateFirst                                            Legal Clearance Letter - Chen and Feng & Schuerfeld (TX) - SurrogateFirst.pdf
320  2025-01-10                  US Surrogacy  drafting                                       25-S-12 Gaillard & Arriaga (UT) - US Surrogacy                                 Agreement for Legal Representation - Gaillard & Arriaga (UT) - US Surrogacy - signed.pdf

In [61]:
# ── Filter by agency (partial match, case-insensitive) ────────────────────────
AGENCY = 'LAS'   # ← change to any agency name or substring

filtered = df[df['agency'].str.contains(AGENCY, case=False, na=False)][['month', 'date', 'agency', 'status', 'case_folder', 'agreement_file']]
print(f'Matching "{AGENCY}": {len(filtered)} cases')
filtered

Matching "LAS": 202 cases

        month        date agency    status                                                                           case_folder                                                                                                           agreement_file
7     2024-01  2024-01-06    LAS  drafting                                                          24-S-02 Zhang & Garcia - LAS                                                   Agreement for Legal Representation - Zhang & Garcia - LAS - signed.pdf
19    2024-02  2024-02-03    LAS  drafting                                                   24-S-21 Yang and Wang & Ochoa - LAS                                            Agreement for Legal Representation - Yang and Wang & Ochoa - LAS - signed.pdf
20    2024-02  2024-02-05    LAS  drafting                                                24-S-19 Peng and Qian & Martinez - LAS                                         Agreement for Legal Representation - Peng and Qian & Martinez - LAS - signed.pdf
21    2024-02  2024-02-07    LAS  drafting                                                24-S-24 Ma and Zhang & Vega (FL) - LAS                                         Agreement for Legal Representation - Ma and Zhang & Vega (FL) - LAS - signed.pdf
22    2024-02  2024-02-14    LAS  drafting                                                           24-S-27 Chiu & Garcia - LAS                                                    (Signed) Agreement for Legal Representation - Chiu & Garcia - LAS.pdf
23    2024-02  2024-02-20    LAS  drafting                                         24-S-35 Feng and Zhao & Sandoval-Maynor - LAS                                  Agreement for Legal Representation - Feng and Zhao & Sandoval-Maynor - LAS - signed.pdf
36    2024-03  2024-03-12    LAS  drafting                                            24-S-50 Ghotb and Karabulut & Flores - LAS                                     Agreement for Legal Representation - Ghotb and Karabulut & Flores - LAS - signed.pdf
37    2024-03  2024-03-15    LAS  drafting                                                     24-S-39 Wang and He & Lopez - LAS                                                                    Garcia-Lopez - GC Attorney Legal Clearance letter.pdf
61    2024-04  2024-04-02    LAS  drafting                                                  24-S-68 Long & Gaspar Carranza - LAS                                           Agreement for Legal Representation - Long & Gaspar Carranza - LAS - Signed.pdf
62    2024-04  2024-04-18    LAS  drafting                                                           24-S-49 Zhao & Garcia - LAS                                                Legal Clearance Letter - Yuhan Zhao & Adilene M. Garcia Rosales - LAS.pdf
63    2024-04  2024-04-23    LAS  drafting                                                 24-S-87 Tian & Herrera-Martinez - LAS                                         Agreement for Legal Representation - Yuan Tian & Mia Martinez - LAS - signed.pdf
64    2024-04  2024-04-25    LAS  drafting                                                    24-S-88 Jiao & Hall (TX -CA) - LAS                                    (Signed) Agreement for Legal Representation - Zemin Jiao & Erin Hall （TX-CA)- LAS.pdf
73    2024-05  2024-05-27    LAS  drafting                                                 24-S-104 Lin and Fah & Fox (IN) - LAS                                           Agreement for Legal Representation - Lin and Fah & Fox (IN) - LAS - signed.pdf
91    2024-06  2024-06-15    LAS  drafting                                                       24-S-100 Uribe & Martinez - LAS     (Revised) Agreement for Legal Representation - Jerry Yang Uribe & Theresa Marie Martinez - LAS 06132024 - signed.pdf
92    2024-06  2024-06-24    LAS  drafting                                                   24-S-118 Li and Zhou & Ovalle - LAS                          Agreement for Legal Representation - Juan Li and Yifan Zhou & Valerie Ovalle - LAS - signed.pdf
106   2024-07  2024-07-12    LAS  drafting                                               24-S-136 Xiao and Zeng & Vollrath - LAS                 Agreement for Legal Representation - Fanglei Xiao and Xianmin Zeng & Jennifer Vollath - LAS - signed.pdf
107   2024-07  2024-07-13    LAS  drafting                                          24-S-135 Sanchez and Hanagami & Pearce - LAS  Agreement for Legal Representation - Leroy Bejarano Sanchez and Kyle Hanagami & Felicia Pearce - LAS 07122024 - sign...
108   2024-07  2024-07-17    LAS  drafting                                            24-S-138 Zhao and Yang & Covarrubias - LAS               Agreement for Legal Representation - Taoxue Zhao and Yongfeng Yang & Lupita Covarrubias - LAS (signed).pdf
109   2024-07  2024-07-28    LAS  drafting                                              24-S-146 Zhao and Sun & Ramos (NV) - LAS               Agreement for Legal Representation - Yaqi Zhao and Jinchao Sun & Amanda Rocio Ramos (NV) - LAS- Signed.pdf
110   2024-07  2024-07-30    LAS  drafting                                                24-S-145 Lee and Chong & Casarez - LAS        Agreement for Legal Representation - Wai Ying Lee and Sai Wa Andy CHong & Alicia Marie Casarez - LAS - signed.pdf
111   2024-07  2024-07-31    LAS  drafting                                                   24-S-148 Chien and Wu & Gomez - LAS                     Agreement for Legal Representation - Pei-Yu Chien and Chun-Yi Wu & Clarissa Gomez - LAS - Signed.pdf
132   2024-08  2024-08-02    LAS  drafting                                                         24-S-149 Chen & Fuentes - LAS                                     Agreement for Legal Representation - Yanyou Chen & Cindy Fuentes  - LAS - Signed.pdf
133   2024-08  2024-08-04    LAS  drafting                                         24-S-156 Yuan Yao & Brittany Ann Camara - LAS                                                     Agreement for Legal Representation - Yao & Camara - LAS - signed.pdf
134   2024-08  2024-08-09    LAS  drafting      24-S-151 Bor Chi John Baptist Chan and Guowei Gavin She & Marilena Sucilla - LAS  Agreement for Legal Representation - Bor Chi John Baptist Chan and Guowei Gavin She & Marilena Sucilla - LAS - signe...
135   2024-08  2024-08-21    LAS  drafting         24-S-168 Nicole Guglielmi and David Guglielmi & Precious Gabby Martinez - LAS      Agreement for Legal Representation - Nicole Guglielmi and David Guglielmi & Precious Martinez - Signed - signed.pdf
136   2024-08  2024-08-23    LAS    review                                                    24-S-171 Ma & Murrilo - LAS review  Agreement for Legal Representation - Liang Ma & Keecemany Alvarez Murrilo and Von Maurice III Haris - LAS review - s...
137   2024-08  2024-08-23    LAS    review                           24-S-172 Feng Gao and Lan Jin & Leslie Badilla - LAS review                     Agreement for Legal Representation - Feng Gao and Lan Jin & Leslie Badilla - LAS review - signed.pdf
138   2024-08  2024-08-25    LAS  drafting                          24-S-174 Na Zhang and Marc Everaerts & Valerie Johnson - LAS                                    Agreement for Legal Representation - Zhang and Everaerts & Johnson - LAS - signed.pdf
139   2024-08  2024-08-28    LAS  drafting                           24-S-175 Shreya Shah and Mitul Shah & Evelyn Valencia - LAS                                                  Agreement for Legal Representation - Shah & Valencia - LAS - signed.pdf
140   2024-08  2024-08-29    LAS  drafting                          24-S-177 Sang Sang and Xinfu Zhi & Abigail Ramos Nunez - LAS                    (Signed) Agreement for Legal Representation - Sang Sang and Xinfu Zhi & Abigail Ramos Nunez - LAS.pdf
141   2024-08  2024-08-29    LAS  drafting                          24-S-179 Ying Wang and Tao Wu & Adrianna Rachelle Cary - LAS                    (Signed) Agreement for Legal Representation - Ying Wang and Tao Wu & Adrianna Rachelle Cary - LAS.pdf
158   2024-09  2024-09-03    LAS    review                                               24-S-182 Luo and Li & Pena - LAS review             Agreement for Legal Representation - Jie Luo and Yingkui Li & Magali Samantha Pena - LAS review - signed.pdf
159   2024-09  2024-09-19    LAS  drafting                                         24-S-165 Sang and Zhi & Lopez Corrales  - LAS                                                                                   GC Attorney Legal Clearance Letter.pdf
160   2024-09  2024-09-21    LAS  drafting                24-S-193 Heather Winters and Michael Coleman & Griselda Verduzco - LAS          Agreement for Legal Representation - Heather Winters and Michael Coleman & Griselda Verduzco - LAS - signed.pdf
161   2024-09  2024-09-24    LAS    review                24-S-200 Qingnan Lin and Danhang Xu & Jasmine Marie Lopez - LAS review          Agreement for Legal Representation - Qingnan Lin and Danhang Xu & Jasmine Marie Lopez - LAS review - signed.pdf
162   2024-09  2024-09-27    LAS    review                               24-S-203 Zhengyi Zhou & Chloe Marie Rapier - LAS review                         Agreement for Legal Representation - Zhengyi Zhou & Chloe Marie Rapier - LAS review - signed.pdf
188   2024-10  2024-10-02    LAS  drafting                                            24-S-212 Po-Wei Chen & Lynzee Dardis - LAS                                      Agreement for Legal Representation - Po-Wei Chen & Lynzee Dardis - LAS - signed.pdf
189   2024-10  2024-10-04    LAS    review                              24-S-213 Zhijun Zhang & Elizabeth Rodriguez - LAS review                        Agreement for Legal Representation - Zhijun Zhang & Elizabeth Rodriguez - LAS review - signed.pdf
190   2024-10  2024-10-08    LAS    review                         24-S-216 Jiakun Wang & Destiny Garcia Valenzuela - LAS review                   Agreement for Legal Representation - Jiakun Wang & Destiny Garcia Valenzuela - LAS review - signed.pdf
191   2024-10  2024-10-08    LAS  drafting                          24-S-218 Liang Deng & Graciela Dorotea Granados Andreu - LAS                    Agreement for Legal Representation - Liang Deng & Graciela Dorotea Granados Andreu - LAS - signed.pdf
192   2024-10  2024-10-10    LAS    review              24-S-221 Katherine Eggert and Kristin Gosney & Noelle Rossi - LAS review                                 Agreement for Legal Representation - Eggert and Gosney & Rossi - LAS review - signed.pdf
193   2024-10  2024-10-11    LAS    review                   24-S-223 Yuqing Shan and Beichen Zhang & Elora Babbini - LAS review                            Agreement for Legal Representation - Shan and Zhang & Elora Babbini - LAS review - signed.pdf
194   2024-10  2024-10-18    LAS  drafting                  24-S-207 Fen Huang and Bin Wei & Venessa Nicole Gonzales Lopez - LAS                                                                                 GC Attorney - Legal Clearance Letter.pdf
195   2024-10  2024-10-20    LAS  drafting                                          24-S-228 Weijie Jiang & Abigail Chavez - LAS                         Signed - Agreement for Legal Representation - Xianjing Zhang & Abigail Chavez - LAS 10202024.pdf
196   2024-10  2024-10-25    LAS    review                          24-S-219 Gulten and Deniz Taner & Kayla Shadden - LAS review                                                                                             IPs Clearance Letter PDF.pdf
197   2024-10  2024-10-28    LAS  drafting                                   24-S-225 Liyun Wang and Hu Lyu & Maria Garcia - LAS                                                                   GC attorney Legal Clearance Letter -  Maria Garcia.pdf
198   2024-10  2024-10-29    LAS  drafting                              24-S-242 Ming Fang and Lin Quan Sun & Nancy Santos - LAS                         Agreement for Legal Representation - Ming Fang and Linquan Sun & Nancy Santos - LAS - Signed.pdf
226   2024-11  2024-11-01    LAS  drafting                    24-S-247 Katherine Wang and Robert Lercari & Alondra Cardona - LAS              Agreement for Legal Representation - Katherine Wang and Robert Lercari & Alondra Cardona - LAS - signed.pdf
227   2024-11  2024-11-05    LAS    review                                     24-S-256 Yiduo Sun & Brianna Fimbrez - LAS review                               Agreement for Legal Representation - Yiduo Sun & Brianna Fimbrez - LAS review - signed.pdf
228   2024-11  2024-11-06    LAS  drafting                                    24-S-252 Po-Wei Chen & Maria Blanca Gonzalez - LAS                              (Signed) Agreement for Legal Representation - Po-Wei Chen & Maria Blanca Gonzalez - LAS.pdf
229   2024-11  2024-11-10    LAS  drafting                            24-S-260 Guanhua Duan and Cheng Wang & Lauren Larsen - LAS             (Signed) Agreement for Legal Representation - Guanhua Duan and Cheng Wang & Lauren Larsen - LAS - signed.pdf
230   2024-11  2024-11-13    LAS    review              24-S-262 Carrol Jun and Young Jun & Erika Elizabeth Fragoso - LAS review                             Agreement for Legal Representation - Jun & Erika Elizabeth Fragoso - LAS review - signed.pdf
231   2024-11  2024-11-13    LAS  drafting                      24-S-263 Pei-Yu Chien and Chun-Yin Wu & Alyssa Sonya Tobon - LAS                 (Signed) Agreement for Legal Representation - Pei-Yu Chien and Chun-Yi Wu & Alyssa Sonya Tobon - LAS.pdf
232   2024-11  2024-11-14    LAS  drafting                      24-S-267 Li Zou and Zhongliang Wang & Sara Sopher Sullivan - LAS                  (signed) Agreement for Legal Representation - Li Zou and Zhongliang Wang & Sara Sopher Sullivan - L.pdf
233   2024-11  2024-11-20    LAS  drafting                     24-S-269 Yifan Ren and Bingchen Chen & Leslie Giselle Yanez - LAS               Agreement for Legal Representation - Yifan Ren and Bingchen Chen & Leslie Giselle Yanez - LAS - signed.pdf
234   2024-11  2024-11-24    LAS  drafting                                             24-S-277 Yanyou Chen & Monica Reyes - LAS                                      Agreement for Legal Representation - Yanyou Chen & Monica Reyes  - LAS - Signed.pdf
259   2024-12  2024-12-02    LAS  drafting  24-S-282 Dennis Cestero-Spruill and Ronnie Cestero-Spruill & Patricia Mancilla - LAS                             Agreement for Legal Representation - Cestero-Spruill  & Patricia Mancilla - LAS - signed.pdf
260   2024-12  2024-12-06    LAS    review                  24-S-291 Winston Hsiao and Julia Nahigian & Jami Maciel - LAS review            Agreement for Legal Representation - Winston Hsiao and Julia Nahigian & Jami Miciel - LAS review - signed.pdf
261   2024-12  2024-12-10    LAS  drafting                     24-S-279 Yang Liu and Pinjun Chen & Amanda Rocio Ramos (NV) - LAS                                                                               Legal Clearance Letter -  Amanda Ramos.pdf
262   2024-12  2024-12-17    LAS  drafting                                     24-S-303 Li Chen and Xuhua Ye & Aimee Barta - LAS                   请签署Agreement for Legal Representation - Li Chen and Xuhua Ye & Aimee Barta - LAS 12172024 - signed.pdf
263   2024-12  2024-12-22    LAS  drafting                  24-S-311 Yan Ma and Haisheng Zhang & Katherine Giselle Cabrera - LAS         (IF Signed) Agreement for Legal Representation - Yan Ma and Haisheng Zhang & Katherine Giselle Cabrera - LAS.pdf
264   2024-12  2024-12-26    LAS    review               24-S-316 Linqi Wang and Gangqiang Fan & Nicolasa Rodriguez - LAS review         Agreement for Legal Representation - Linqi Wang and Gangqiang Fan & Nicolasa Rodriguez - LAS review - signed.pdf
303   2025-01  2025-01-02    LAS  drafting                          25-S-04 Ran Xu and Bo Zhao & Ana Laura Aviles Castillo - LAS                   (Signed) Agreement for Legal Representation - Ran Xu and Bo Zhao & Ana Laura Aviles Castillo - LAS.pdf
304   2025-01  2025-01-04    LAS  drafting                                           25-S-03 Yanyou Chen & Ashley Carrillo - LAS                                 请签署Agreement for Legal Representation - Yanyou Chen & Ashley Carrillo - LAS - signed.pdf
305   2025-01  2025-01-09    LAS  drafting             25-S-14 Haoxue Zhu and Yifeng Cao & Jennifer Marisol Rivera Quntero - LAS              (Signed) Agreement for Legal Representation - Haoxue Zhu and Yifeng Cao & Jennifer Rivera Quntero - LAS.pdf
306   2025-01  2025-01-15    LAS  drafting   24-S-312 Mayumi Nishiyama and Kentaro Abe & Adriana Flores and James Robinett - LAS                                                                                     legal clearance letter  Adriana .pdf
307   2025-01  2025-01-16    LAS  drafting                      25-S-19 Xiaojun Zhu and Hongzhan Li & Ebelin Oropeza Perez - LAS          (signed) Agreement for Legal Representation -  Xiaojun Zhu and Hongzhan Li & Ebelin Oropeza Perez - LAS (2).pdf
308   2025-01  2025-01-20    LAS    review                                      25-S-23 Jing Yang & Marisol Sliakis - LAS review                              (Signed) Agreement for Legal Representation -  Jing Yang & Marisol Sliakis - LAS review.pdf
309   2025-01  2025-01-21    LAS  drafting                         25-S-30 Yuan-Hsin Chang and Jia-Lin Liu & Diana Arteaga - LAS                 (Signed) Agreement for Legal Representation -  Yuan-Hsin Chang and Jia-Lin Liu & Diana Arteaga - LAS.pdf
310   2025-01  2025-01-23    LAS  drafting                               25-S-35 Yifan Ren and Bingchen Chen & Lizet Bravo - LAS                       (Signed) Agreement for Legal Representation - Yifan Ren and Bingchen Chen & Lizbet Bravo - LAS.pdf
311   2025-01  2025-01-27    LAS    review               25-S-24 Christine Bohm and Friedrich Bohm & Lauren Bashara - LAS review                              Full Legal Clearance Letter -  Christine Bohm and Friedrich Bohm & Lauren Bashara - LAS.pdf
312   2025-01  2025-01-29    LAS  drafting                        25-S-29 Maria Ito and Takahiro Ito & Rubi Julia Balderas - LAS                (Signed) Agreement for Legal Representation -  Maria Ito and Takahiro Ito & Rubi Julia Balderas - LAS.pdf
335   2025-02  2025-02-02    LAS  drafting                         25-S-38 Zi Yang and Kun Chen & Rosalinda Marie Delarosa - LAS                 (Signed) Agreement for Legal Representation - Zi Yang and Kun Chen  & Rosalinda Marie Delarosa - LAS.pdf
336   2025-02  2025-02-07    LAS  drafting                                       25-S-52 Yanyou Chen & Alejandra Esquivias - LAS                           请签署 Agreement for Legal Representation - Yanyou Chen & Alejandra Esquivias  - LAS - signed.pdf
337   2025-02  2025-02-11    LAS  drafting                                       25-S-55 Nancy Ramirez Lim & Erica Sanchez - LAS                          Agreement for Legal Representation - Nancy Ramirez Lim & Erica Marie Sanchez - LAS - signed.pdf
338   2025-02  2025-02-18    LAS  drafting                            25-S-59 Feng Feng and Heping Zhang & Rachelyn Ummels - LAS                     (Signed) Agreement for Legal Representation - Feng Feng and Heping Zhang & Rachelyn Ummels - LAS.pdf
339   2025-02  2025-02-18    LAS  drafting                                   25-S-60 Yanxue Shao & Elizabeth Padilla Barva - LAS                         请签署Agreement for Legal Representation - Yanxue Shao & Elizabeth Padilla Barva - LAS - signed.pdf
360   2025-03  2025-03-01    LAS  drafting                         25-S-69 Blake Jiaxin Li and Zijuan Wu & Robin Hernandez - LAS                  Agreement for Legal Representation - Zijuan Wu and Blake Jiaxin Li & Robin Hernandez - LAS - signed.pdf
361   2025-03  2025-03-04    LAS  drafting                                   25-S-66 Ying Xue and Liang Liu & Ashley Hance - LAS                     (Signed) Agreement for Legal Representation - Ying Xue and Liang Liu & Ashley Nicole Hance - LAS.pdf

In [62]:
# ── Filter by status ──────────────────────────────────────────────────────────
STATUS = 'review'   # ← 'review' or 'drafting'

filtered = df[df['status'] == STATUS][['month', 'date', 'agency', 'case_folder', 'agreement_file']]
print(f'Status={STATUS!r}: {len(filtered)} cases')
filtered

Status='review': 321 cases

        month        date                                 agency                                                                                  case_folder                                                                                                           agreement_file
1     2024-01  2024-01-11                 All Families Surrogacy                    24-S-05 Santelli and Hagood & Severn - Review (WA) All Families Surrogacy                           Agreement for Legal Representation - Santelli and Hagood & Severn review (WA) AFS - signed.pdf
2     2024-01  2024-01-22          California Surrogacy Partners                                          24-S-08 Latner and Feldstein & Freytag - Review CSP                       Agreement for Legal Representation - Latner and Feldstein & Freytag - Review - CSP - IM Signed.pdf
3     2024-01  2024-01-08                  Giving Tree Surrogacy                                     24-S-03 Ding & Martinez - Giving Tree Surrogacy (Review)                                                     Agreement for Legal Representation- Martinez GTS review - signed.pdf
4     2024-01  2024-01-18                  Giving Tree Surrogacy                                      24-S-07 Watters and Mastrodonato & Carli - Review - GTS                        Agreement for Legal Representation - Watters and Mastrodonato & Carli - Review - GTS - signed.pdf
8     2024-01  2024-01-22                          Pitter Patter                                                          24-S-10 Werner review Pitter Patter                               Agreement for Legal Representation - Jovanoic & Werner - Pitter Patter review - Signed.pdf
9     2024-01  2024-01-31                          Pitter Patter                                             24-S-18 Corradi & DeBiase - Review Pitter Patter                                Agreement for Legal Representation - Sierra DeBiase - Review - Pitter Patter - signed.pdf
13    2024-02  2024-02-27          California Surrogacy Partners                                           24-S-26 Kohler and Richards & Nelson UT review CSP                                                                                            IP Legal Clearance Letter.pdf
14    2024-02  2024-02-29                            Dreamweaver                                24-S-41 Zhuang and Abrams & Butteweg -Dreamweaver review (AZ)                                                      GC -Agreement for Legal Representation - Butteweg (AZ) - signed.pdf
17    2024-02  2024-02-21                  Giving Tree Surrogacy                                                          24-S-31 Chang and Hedges review GTS                                           Agreement for Legal Representation - Chang & Hedges review (AZ) GTS signed.pdf
24    2024-02  2024-02-02                           Surrogacy.is                                                     24-S-17 Bell & Smith review Surrogacy.is                                  Agreement for Legal Representation - Smith and Hyler review - Surrogacy.is - signed.pdf
33    2024-03  2024-03-01                                   Indy                                                24-S-44 Dowling & Cartwright review (IL) indy                                       Agreement for Legal Representation - Dowling & Cartwright review (IL) - signed.pdf
34    2024-03  2024-03-22                                   Indy                                                         24-S-45 Tucknott & Howes indy review                                                   Legal Clearance Letter - Tucknott and Shanahan & Howes indy review.pdf
39    2024-03  2024-03-26                                    OFG                                                           24-S-48 Liu & Cossyleon OFG review                                                            Legal Clearance Letter - Liu-Cossyleon - Life IVF - Omega.pdf
40    2024-03  2024-03-06                            OFG & Stork                                          24-S-42 Redestad & Grimes - OFG & Stork review (IL)                                                     Agreement for Legal Representation - Grimes review (IL) - signed.pdf
41    2024-03  2024-03-21                              Oceanside                                              24-S-53 Jiang and Rios review  (HI) - Oceanside                                Agreement for Legal Representation - Jiang and Rios review  (HI) - Oceanside - signed.pdf
43    2024-03  2024-03-22  Pinnacle Surrogacy review (withdrawn)                             24-S-61 Xu & Benson (WA) - Pinnacle Surrogacy review (withdrawn)                                              Agreement for Legal Representation - (WA) Xu & Benson - Review - signed.pdf
46    2024-03  2024-03-16                         SurrogateFirst                                        24-S-55 Christina Wilkey (OK) review - SurrogateFirst                                    Agreement for Legal Representation- Chrisina Wilke (OK) - SurrogateFirst - signed.pdf
49    2024-04  2024-04-29                          Abundant Life                                     24-S-92 Alfani and Ianieri & Bird - Abundant Life review                                                            Agreement for Legal Representation review - Bird - signed.pdf
51    2024-04  2024-04-03                              Babiology                                         24-s-66 Zhang and Deng & Melendez - Babiology review                                         Agreement for Legal Representation review Zhang and Deng & Melendez - signed.pdf
52    2024-04  2024-04-29                           Egg Donation                 24-S-71 Engelberg and Hodorov & Schwank (IL) OFG & Stork Egg Donation review                                                                              Legal Clearance Letter - Schwank review.pdf
53    2024-04  2024-04-02                              Elite IVF                                                   24-S-60 Li & Taylor (AZ) -Elite IVF review                                    Agreement for Legal Representation -  Li & Taylor (AZ) -Elite IVF review - signed.pdf
54    2024-04  2024-04-10                                    FSC                                                   24-S-81 Lu and Li & Giminez - Review - FSC                                                         Agreement for Legal Representation - Giminez Review - signed.pdf
56    2024-04  2024-04-17                  Giving Tree Surrogacy                                                         24-S-73 Chen & Drummond - GTS review                                                                                           Clearance.S.Patel.04.17.24.pdf
57    2024-04  2024-04-23                  Giving Tree Surrogacy                                           24-S-83 Chen and Zheng & Alvarez-Woolen GTS review                                Legal Clearance Letter - Chen and Zheng & Alvarez-woolen giving tree surrogacy review.pdf
58    2024-04  2024-04-23                  Giving Tree Surrogacy                                                   24-S-90 Dong and Wang & Ortiz - GTS review             Agreement for Legal Representation - Dong and Wang & Ortiz - Giving Tree review - signed-DESKTOP-MU9IT8J.pdf
59    2024-04  2024-04-29                  Giving Tree Surrogacy                                                  24-S-94 Peng and Lin & Vasquez - GTS review                                      Agreement for Legal Representation - Peng and Lin & Vasquez - GTS review signed.pdf
65    2024-04  2024-04-18                       StrongerTogether                             24-S-75 Malik and Luthra & Bickel review (WA) - StrongerTogether           (GCH signed) Agreement for Legal Representation - Malik and Luthra & Bickel review (WA) - StrongerTogether.pdf
71    2024-05  2024-05-01                                   Indy                                                             24-S-77 Ren & Franco review indy                                                (Wrong, for review) Legal Clearance Letter - Ren & Franco review indy.pdf
77    2024-05  2024-05-19             StrongerTogether review NV                                       24-S-99 Atkinson & Burrow - StrongerTogether review NV                   Agreement for Legal Representation - Atkinson & Burrow - StrongerTogetherSurrogacy review - signed.pdf
82    2024-05  2024-05-08                   West Coast Surrogacy                                       24-S-96 Karrtik & Arvizu - West Coast Surrogacy review                         Agreement for Legal Representation  -  Timke and Schueling AsiaWest-DESKTOP-MU9IT8J - signed.pdf
88    2024-06  2024-06-21                  Giving Tree Surrogacy                                                   24-S-112 Du and Wu & Brockman - GTS review                     Agreement for Legal Representation - Du and Wu & Brockman and Dickinson (AZ) GTS review - signed.pdf
93    2024-06  2024-06-18                                    OFG                                                         24-S-110 Wong & Carmona - OFG review                                                                              Legal Clearance GSA Life- Wong- Carmona.pdf
94    2024-06  2024-06-14                   Reproductive Options                                    24-S-106 Shah & Hedges - Reproductive Options review (AZ)                               Agreement for Legal Representation- Shah & O'Brien (AZ)  Reproductive Options - signed.pdf
97    2024-07  2024-07-15                                  Alcea                                     24-S-137 Snapp and Sultan & Bojorquez (AZ) Review -Alcea                  Agreement for Legal Representation review- Snapp and Sultan & Bojorquez (AZ) Review -Alcea - signed.pdf
98    2024-07  2024-07-08                               All Love                               24-S-131 He and Luan & Harris review (WA) - All Love Surrogacy                    Agreement for Legal Representation - He and Luan & Harris (WA) Review - AllLoveSurrogacy - signed.pdf
100   2024-07  2024-07-09                                   FTSC                                                    24-S-132 Alexa Guevara review (TX) - FTSC                                                Agreement for Legal Representation - Alexa Guevara review TX - signed.pdf
103   2024-07  2024-07-09                  Giving Tree Surrogacy                                            24-S-133 Kang and Lu & Hermadez review (AZ) - GTS                               Agreement for Legal Representation - Kang and Lu & Hernadez (AZ) Review - GTS - signed.pdf
115   2024-07  2024-07-25                           Surrogacy.is                                              24-S-144 Enayati & Felipe - Surrogacy.is Review                                 Agreement for Legal Representation - Enayati & Felipe - Surrogacy.is Review - signed.pdf
116   2024-07  2024-07-30                           Surrogacy.is                                         24-S-147 Schaefer & Ramirez (AZ) Surrogacy.is Review                               Agreement for Legal Representation - Schaefer & Ramirez - Surrogacy.is Review - signed.pdf
127   2024-08  2024-08-07                                   Indy                                                         24-S-134 Desai & Simes - Review INDY                                                            Legal Clearance Letter - Desai and Johnson & Simes - INDY.pdf
136   2024-08  2024-08-23                                    LAS                                                           24-S-171 Ma & Murrilo - LAS review  Agreement for Legal Representation - Liang Ma & Keecemany Alvarez Murrilo and Von Maurice III Haris - LAS review - s...
137   2024-08  2024-08-23                                    LAS                                  24-S-172 Feng Gao and Lan Jin & Leslie Badilla - LAS review                     Agreement for Legal Representation - Feng Gao and Lan Jin & Leslie Badilla - LAS review - signed.pdf
142   2024-08  2024-08-22                        Newgen Families                                    24-S-166 Madonna and Magri & Garcia (IL) - New Gen review                      Agreement for Legal Representation  - Madonna and Magri & Garcia (IL) - New Gen review - signed.pdf
145   2024-08  2024-08-13                       surroconnections                                       24-S-164 Sfeir and Sirvain PBO review surroconnections               Agreement for Legal Representation - Sfeir and Sirvain & Kanso -  PBO review Surroconnections - signed.pdf
147   2024-09  2024-09-28           Blossom California Fertility                           24-S-202 Wang & Benovic (OH) - Blossom California Fertility review              Agreement for Legal Representation - Wang & Benovic (OH) - Blossom California Fertility review - signed.pdf
150   2024-09  2024-09-03              Family Source Consultants                                  24-S-167 Sheth & Bastida - review Family Source Consultants                                                                    Legal Clearance Letter - Sheth & Bastida - review.pdf
153   2024-09  2024-09-23                                   Indy                                                      24-S-178 Butler & Caughey - Review Indy                                                                                Full Legal Clearance-Butler-Caughey-2.pdf
158   2024-09  2024-09-03                                    LAS                                                      24-S-182 Luo and Li & Pena - LAS review             Agreement for Legal Representation - Jie Luo and Yingkui Li & Magali Samantha Pena - LAS review - signed.pdf
161   2024-09  2024-09-24                                    LAS                       24-S-200 Qingnan Lin and Danhang Xu & Jasmine Marie Lopez - LAS review          Agreement for Legal Representation - Qingnan Lin and Danhang Xu & Jasmine Marie Lopez - LAS review - signed.pdf
162   2024-09  2024-09-27                                    LAS                                      24-S-203 Zhengyi Zhou & Chloe Marie Rapier - LAS review                         Agreement for Legal Representation - Zhengyi Zhou & Chloe Marie Rapier - LAS review - signed.pdf
168   2024-09  2024-09-30                          Pitter Patter                                 24-S-209 Galipo and Riggio & Pubill - review - Pitter Patter                       Agreement for Legal Representation - Galipo and Riggo & Pubill - Pitter Patter Review - signed.pdf
170   2024-09  2024-09-04                     Shining Light Baby                                         24-S-181 Xu & Lewis (AL) - Shining Light Baby review                                   Agreement for Legal Representation - Xu & Lewis (AL) - Shining Light Baby - signed.pdf
174   2024-10  2024-10-30                         Babies Sprouts                                                24-S-244 Chen & Salas - Babies Sprouts review                                   Agreement for Legal Representation - Chen & Salas - Babies Sprouts review - signed.pdf
176   2024-10  2024-10-08           Blossom California Fertility                       24-S-217 Feng & Rivera (AL - CA) - Blossom California Fertility review   Agreement for Legal Representation - Feng & Rivera (AL-CA) - Blossom California Fertility review 10072024 - signed.pdf
177   2024-10  2024-10-23           Blossom California Fertility                              24-S-238 Lin & Sales (SC) - Blossom California Fertility Review                      Agreement for Legal Representation - Lin & Sales - Blossom California Fertility review - signed.pdf
179   2024-10  2024-10-03                      Choices Donations                                   24-S-215 Thornhill & Munoz (AZ) - Choices Donations review                                                  Agreement for Legal Representation- Thornhill & Munoz (AZ) - signed.pdf
182   2024-10  2024-10-31                  Giving Tree Surrogacy                             24-S-240 Safaei-Far & Darrah (WA) - Giving Tree Surrogacy review                 Agreement for Legal Representation- Safaei-Far & Darrah (WA) - Giving Tree Surrogacy review - signed.pdf
183   2024-10  2024-10-21                                   Indy                                                       24-S-233 Owens & Herrera - Indy review                                Agreement for Legal Representation - Doust and Owens & Herrera - Indy review - signed.pdf
185   2024-10  2024-10-21                     Ivy Baby Surrogacy                                           24-S-173 Bao & Brandau - Ivy Baby Surrogacy review                                                                                       Clearance Letter to Doctor (2).pdf
186   2024-10  2024-10-22                     Ivy Baby Surrogacy                                     24-S-236 Zhi and Yan & Dukes - Ivy Baby Surrogacy review                                  Agreement for Legal Representation - Zhi and Yan & Dukes - Ivy Baby review - signed.pdf
187   2024-10  2024-10-25                     Ivy Baby Surrogacy                                   24-S-239 Chen and Dai & Mutter - Ivy Baby Surrogacy review                             Agreement for Legal Representation - Chen and Dai & Mutter - Ivy Baby Surrogacy - signed.pdf
189   2024-10  2024-10-04                                    LAS                                     24-S-213 Zhijun Zhang & Elizabeth Rodriguez - LAS review                        Agreement for Legal Representation - Zhijun Zhang & Elizabeth Rodriguez - LAS review - signed.pdf
190   2024-10  2024-10-08                                    LAS                                24-S-216 Jiakun Wang & Destiny Garcia Valenzuela - LAS review                   Agreement for Legal Representation - Jiakun Wang & Destiny Garcia Valenzuela - LAS review - signed.pdf
192   2024-10  2024-10-10                                    LAS                     24-S-221 Katherine Eggert and Kristin Gosney & Noelle Rossi - LAS review                                 Agreement for Legal Representation - Eggert and Gosney & Rossi - LAS review - signed.pdf
193   2024-10  2024-10-11                                    LAS                          24-S-223 Yuqing Shan and Beichen Zhang & Elora Babbini - LAS review                            Agreement for Legal Representation - Shan and Zhang & Elora Babbini - LAS review - signed.pdf
196   2024-10  2024-10-25                                    LAS                                 24-S-219 Gulten and Deniz Taner & Kayla Shadden - LAS review                                                                                             IPs Clearance Letter PDF.pdf
204   2024-10  2024-10-21                      Stronger Together                  24-S-227 Bonnet and Cauchois & YaDullah (MO) PBO Review - Stronger Together                                                  Agreement for Legal Representation - YaDullah - PBO review - signed.pdf
210   2024-11  2024-11-08           Blossom California Fertility                  24-S-257 Li & Valdez and Amador (TX-CA) Blossom California Fertility review   Agreement for Legal Representation - Li & Valdez and Amador (TX-CA) - Blossom California Fertility review - signed.pdf
212   2024-11  2024-11-11           Blossom California Fertility                       24-S-210 Zhong and Hu & Kraus (WI) Blossom California Fertility review                          Legal Clearance Letter - Zhong and Hu & Samantha Kraus (WI CA)-Blossom California Fertility.pdf
213   2024-11  2024-11-14           Blossom California Fertility                              24-S-253 Li & Pirela (FL) - Blossom California Fertility review                      Agreement for Legal Representation - Li & Pirela - Blossom California Fertility review - signed.pdf

In [63]:
# ── Search case folder name ───────────────────────────────────────────────────
SEARCH = '25-S-14'   # ← any substring of the folder name

df[df['case_folder'].str.contains(SEARCH, case=False, na=False)]

       month        date                        agency    status                                                                case_folder                                                                                                   agreement_file            source  path_len
305  2025-01  2025-01-09                           LAS  drafting  25-S-14 Haoxue Zhu and Yifeng Cao & Jennifer Marisol Rivera Quntero - LAS      (Signed) Agreement for Legal Representation - Haoxue Zhu and Yifeng Cao & Jennifer Rivera Quntero - LAS.pdf  signed agreement       274
389  2025-04  2025-04-23                Blissful Bloom  drafting                                 25-S-141 Yu and Liu & Lee - Blissful Bloom                              Agreement for Legal Representation - Yu and Liu & Lee - Blissful Bloom - signed.pdf  signed agreement       219
395  2025-04  2025-04-26  Blossom California Fertility    review     25-S-144 Luo and Lyu & Cupp (TX) - Blossom California Fertility review  (Signed) Agreement for Legal Representation - Luo and Lyu & Cupp (TX) - Blossom California Fertility review.pdf  signed agreement       275
403  2025-04  2025-04-23         Giving Tree Surrogacy  drafting                                   25-S-143 Lu and Huang & Lamin (OH) - GTS                            请签署Agreement for Legal Representation -  Lu and Huang & Lamin (OH) - GTS - signed.pdf  signed agreement       219
410  2025-04  2025-04-28                           LAS  drafting                 25-S-146 Pei-Yu Chien and Chun-Yi Wu & Cecilia Perez - LAS              Agreement for Legal Representation - Pei-Yu Chien and Chun-Yi Wu & Cecilia Perez - LAS - Signed.pdf  signed agreement       251
411  2025-04  2025-04-30                           LAS  drafting            25-S-147 Xiuhong Hu and Chao-Yang Chan & Cassandra Moreno - LAS      请签署Agreement for Legal Representation - Xiuhong Hu and Chao-Yang Chan & Cassandra Moreno - LAS - signed.pdf  signed agreement       264
412  2025-04  2025-04-24                     Lily Baby  drafting                    25-S-140 Guo and Zhu & Perez (IL) - Lily Baby Surrogacy               (Signed) Agreement for Legal Representation - Guo and Zhu & Perez (IL) - Lily Baby Surrogacy_2.pdf  signed agreement       247
422  2025-04  2025-04-30                SurrogateFirst  drafting                      25-S-149 Hammond III and Weyker (NY) - SurrogateFirst                   Agreement for Legal Representation - Hammond III and Weyker (NY) - SurrogateFirst - signed.pdf  signed agreement       241
430  2025-05  2025-05-06               Dream Surrogacy  drafting                                   25-S-145 Moore & Aaron - Dream Surrogacy                                Agreement for Legal Representation - Moore & Aaron - Dream Surrogacy - signed.pdf  signed agreement       215
442  2025-05  2025-05-02                           LAS    review                            25-S-148 Jia Li & Dailenea Heffron - LAS review                         Agreement for Legal Representation - Jia Li & Dailenea Heffron - LAS review - signed.pdf  signed agreement       229

In [64]:
# ── All cases sorted by case number (24-S-01 first, most recent at bottom) ────

def _case_sort_key(folder):
    m = re.match(r'^(\d{2})-[A-Za-z]+-?(\d+)', folder)
    return (int(m.group(1)), int(m.group(2))) if m else (99, 99999)

sorted_df = df.copy()
sorted_df['_key'] = sorted_df['case_folder'].apply(_case_sort_key)
sorted_df = (sorted_df
             .sort_values('_key')
             .drop(columns='_key')
             .reset_index(drop=True))
sorted_df.index = range(1, len(sorted_df) + 1)
sorted_df.index.name = '#'
print(f'Total: {len(sorted_df)} cases')
sorted_df[['month', 'date', 'agency', 'status', 'case_folder', 'agreement_file']]

Total: 1090 cases

        month        date                          agency    status                                                                            case_folder                                                                                                           agreement_file
#
1     2024-01  2024-01-08               Kindred Surrogacy  drafting                                  24-S-01 Wu and Yang & Wilson (CA) - Kindred Surrogacy                            Agreement for Legal Representation - Wu and Yang & Wilson (CA) Kindred Surrogacy - signed.pdf
2     2024-01  2024-01-06                             LAS  drafting                                                           24-S-02 Zhang & Garcia - LAS                                                   Agreement for Legal Representation - Zhang & Garcia - LAS - signed.pdf
3     2024-01  2024-01-08           Giving Tree Surrogacy    review                               24-S-03 Ding & Martinez - Giving Tree Surrogacy (Review)                                                     Agreement for Legal Representation- Martinez GTS review - signed.pdf
4     2024-01  2024-01-12                  SurrogateFirst  drafting                                              24-S-04 Wang & Moritz (WA) SurrogateFirst                                      Agreement for Legal Representation - Wang & Mortiz (WA) SurrogateFirst - signed.pdf
5     2024-01  2024-01-11          All Families Surrogacy    review              24-S-05 Santelli and Hagood & Severn - Review (WA) All Families Surrogacy                           Agreement for Legal Representation - Santelli and Hagood & Severn review (WA) AFS - signed.pdf
...       ...         ...                             ...       ...                                                                                    ...                                                                                                                      ...
1086  2026-06  2026-06-09                            EDSI  drafting                                      26-S-281 Gottpati and Shiak & Rhoades (AZ) - EDSI                               Agreement for Legal Representation - Gottpati and Shiak & Rhoades (AZ) - EDSI - signed.pdf
1087  2026-06  2026-06-10         The Fertility Solutions  drafting                         26-S-282 Ma and Fang & Tonkovich - The Fertility Solutions LLC                  (Signed) Agreement for Legal Representation - Ma and Fang & Tonkovich - The Fertility Solutions LLC.pdf
1088  2026-06  2026-06-10                     One Village  drafting                                      26-S-283 Hung & Ward (KY) - One Village Surrogacy                            请签署Agreement for Legal Representation - Hung & Ward (KY) - One Village Surrogacy - signed.pdf
1089  2026-06  2026-06-09  Family Solutions International    review  26-S-285 Barron and Jubert & Castleberry (AZ) - Family Solutions International review  Agreement for Legal Representation - Barron and Jubert & Castleberry (AZ) - Family Solutions International review - ...
1090  2025-07  2025-07-23           Giving Tree Surrogacy  drafting                                                   25-S-XXXX Huang & Mcaffee (UT) - GTS                                                                      McAfee Conditional Medical Clearance Letter (2).pdf

[1090 rows x 6 columns]

In [65]:
# ── Case folders still missing (no signed agreement and no clearance letter) ───

def _case_sort_key(folder):
    m = re.match(r'^(\d{2})-[A-Za-z]+-?(\d+)', folder)
    return (int(m.group(1)), int(m.group(2))) if m else (99, 99999)

def _missing_reason(folder_name, files):
    fn = folder_name.lower()
    if 'terminat' in fn:
        return 'case terminated'
    if 'not to represent' in fn or 'decide not' in fn or 'declined' in fn:
        return 'decided not to represent'
    if not files:
        return 'empty folder'
    img_exts = {'.pdf', '.jpg', '.jpeg', '.png', '.gif', '.tiff', '.bmp'}
    has_agreement_pdf = any(
        any(f.lower().endswith(e) for e in img_exts)
        and 'agreement' in f.lower() and 'legal' in f.lower() and 'representation' in f.lower()
        for f in files
    )
    if has_agreement_pdf:
        return 'agreement exists but not marked as signed'
    if any('agreement' in f.lower() for f in files):
        return 'agreement file found but wrong format/name'
    return 'no agreement file in folder'

missing = []

for folder_name in sorted(os.listdir(BASE_DIR)):
    if folder_name.startswith('.') or folder_name.startswith('~'):
        continue
    folder_path = os.path.join(BASE_DIR, folder_name)
    if not os.path.isdir(folder_path):
        continue
    if not (folder_name.startswith('24-') or folder_name.startswith('25-') or folder_name.startswith('26-')):
        continue
    parsed = parse_folder_name(folder_name)
    if not parsed:
        continue
    raw_agency, _ = parsed
    if not normalize_agency_name(raw_agency):
        continue
    if find_agreement_file(folder_path) or find_clearance_letter(folder_path):
        continue  # already counted in df

    case_no = folder_name.split()[0]
    try:
        files = sorted(e.name for e in os.scandir(folder_path) if e.is_file())
    except:
        files = []

    missing.append({
        'case_no':     case_no,
        'case_folder': folder_name,
        'reason':      _missing_reason(folder_name, files),
        'files':       '\n'.join(files) if files else '(empty folder)',
    })

miss_df = pd.DataFrame(missing)
if len(miss_df):
    miss_df['_sort'] = miss_df['case_no'].apply(lambda c: _case_sort_key(c + ' '))
    miss_df = miss_df.sort_values('_sort').drop(columns='_sort').reset_index(drop=True)
    miss_df.index = range(1, len(miss_df) + 1)
    miss_df.index.name = '#'

print(f'Still missing (no agreement and no clearance letter): {len(miss_df)}')
pd.set_option('display.max_rows', 2000)
pd.set_option('display.max_colwidth', 300)
miss_df

Still missing (no agreement and no clearance letter): 72

,case_no,case_folder,reason,files
#,,,,
1,24-S-11,24-S-11 Uribe & Bowman - LAS,empty folder,(empty folder)
2,24-S-11,24-S-11 Uribe & Bowman - LAS - TERMINATE4D,case terminated,Agreement for Legal Representation - Uribe & Bowman - LAS.docx\nAgreement for Legal Representation - Uribe & Bowman - LAS.pdf\nFIRST DRAFT Gestational Surrogacy Agreement - Uribe & Bowman - LAS 01282024.docx\nFIRST DRAFT Gestational Surrogacy Agreement - Uribe & Bowman - LAS 01282024.pdf\nIntern...
3,24-S-23,24-S-23 (ON HOLD) Independent Surrogacy - Yang & Shevshenko,agreement exists but not marked as signed,(Internal Drafting) Gestational Surrogacy Agreement - Yang & Shevshenko - independent.docx\nAgreement for Legal Representation - Yang & Shevshenko.docx\nAgreement for Legal Representation - Yang & Shevshenko.pdf\nCompleted Match Sheet - Yang - Independant Surrogacy Match.pdf
4,24-S-29,24-S-29 Wang and Chen & Willhite BBB (MO) nmc,empty folder,(empty folder)
5,24-S-32,24-S-32 Kazmi & Zachariadis and Gutierrez PBO review Surroconnections,agreement exists but not marked as signed,Agreement for Legal Representation - Kazmi & Zachariadis and Gutierrez PBO review Surroconnections.docx\nAgreement for Legal Representation - Kazmi & Zachariadis and Gutierrez PBO review Surroconnections.pdf\nAgreement for Legal Representation.doc\nAhmed.png\nCertified Judgment - Kazmi and Zacha...
6,24-S-46,24-S-46 Dollinger & Soto - Reproductive Options review,agreement exists but not marked as signed,Agreement for Legal Representation - Dollinger & Soto .docx\nAgreement for Legal Representation - Dollinger & Soto .pdf\nGC Maria match sheet.pdf
7,24-S-51,24-S-51 Angwang and Velez review - New Gen (AZ),agreement exists but not marked as signed,Agreement for Legal Representation - Angwang and Velez review - New Gen (AZ).docx\nAgreement for Legal Representation - Angwang and Velez review - New Gen (AZ).pdf\nGestational Surrogacy Agreement - Angwang and Velez review - New Gen (AZ).pdf\nLuozhu & Li - Raquel & Austin.GS.d1.docx\nLuozhu & L...
8,24-S-54,24-S-54 Li and Cheng & Sanchez - LAS - NEED A REMATCH,no agreement file in folder,"Flor S. Benefit package (signed).pdf\nFlor Sanchez, Match sheet.pdf\nMatch Info.pdf\nunnamed.jpg"
9,24-S-76,24-S-76 Sampat & Dorman - Pitter Patter (FL),agreement exists but not marked as signed,Agreement for Legal Representation -Sampat.docx\nAgreement for Legal Representation -Sampat.pdf\nBryanne_Benefit_Packet-bryannedorman_gmail.com.pdf\nCompare GSA Sampat.pdf\nCompare Internal Draft -Gestational Surrogacy Agreement - Sampat & Dorman Pitter Patter.docx\nDRAFT Gestational Surrogacy A...
10,24-S-80,24-S-80 Liu and Li & Jilian Cring - Flying Stork review - TERMINATED,case terminated,1ofOr53_(Signed) 缴费安排.pdf\nAgreement for Legal Representation review - Jillian Cring - Flying Stork review.docx\nAgreement for Legal Representation review - Jillian Cring - Flying Stork review.pdf\nGSA V1 clean - Huiping Liu and Ting Li - GC Jillian Cring.docx\nGSA V1 clean - Huiping Liu and Tin...
11,24-S-84,24-S-84 Angwang and Zeng & Velez (AZ) - New Gen review,agreement exists but not marked as signed,Agreement for Legal Representation - Angwang and Zeng & Velez and Chambers (AZ) NewGen Families review.docx\nAgreement for Legal Representation - Angwang and Zeng & Velez and Chambers (AZ) NewGen Families review.pdf\nLuozhu & Li - Raquel & Austin.GS.d1.docx\nRaquel Alice Lucas Match Sheet.pdf\nR...
12,24-S-163,24-S-163 Zhuang & Aguilar - LAS review NMC,no agreement file in folder,Letter to IVF Clinic - Jessica Aguilar - LAS.docx\nLetter to IVF Clinic - Jessica Aguilar - LAS.pdf\nunnamed.jpg
13,24-S-169,24-S-169 Grushik and Serrato Agency agreement review - Conceivabilities,agreement exists but not marked as signed,2023_All-In_Service_Agreement_-_Hrushyk__-_Garcia.pdf\nAgreement for Legal Representation - Hrushyk and Serrato agency review - Conceivabilities.docx\nAgreement for Legal Representation - Hrushyk and Serrato agency review - Conceivabilities.pdf
14,24-S-184,24-S-184 Liao and Zhao & Jimenez (FL) - FSC,agreement exists but not marked as signed,1.docx\n2024-06-25 GC REDLINE Gestational Surrogacy Agreement - Yu and Liu & Hillman (FL) 6-25-24.pdf\nAgreement for Legal Representation - Liao and Zhao & Jimenez (FL) - FSC.docx\nAgreement for Legal Representation - Liao and Zhao & Jimenez (FL) - FSC.pdf\nDRAFT - Gestational Surrogacy Agreemen...
15,24-S-190,24-S-190 Gaillard and Proteau & Velazquez - SurrogateFirst (NV),agreement exists but not marked as signed,7029KV-NV_Gaillard_Match_Sheet.pdf\nAgreement for Legal Representation - Gaillard and Proteau & Velazquez - SurrogateFirst (NV)-Ralph-work-laptop.pdf\nAgreement for Legal Representation - Gaillard and Proteau & Velazquez - SurrogateFirst (NV).docx\nAgreement for Legal Representation - Gaillard a...
16,24-S-194,24-S-194 Bartelo - LAS contract review,agreement file found but wrong format/name,Laquita G. LAS Benefit Package- Current version 2.pdf\nPaola Barragan_ Giuseppe (Joe) Pandolfo- Cost Estimate- GC Laquita- Revised.pdf\nPaola Barragan_ Giuseppe Pandolfo- Agency Agreement- Revised .pdf\nTransaction Reporting.pdf\nicon_3_pdf_x16.png
17,24-S-283,24-S-283 Yue Wang and Tingmei Hou & Sophia Miranda Garcia - LAS review ON HOLD,agreement exists but not marked as signed,Agreement for Legal Representation - Yue Wang and Tingmei Hou & Sophia Miranda Garcia - LAS review.docx\nAgreement for Legal Representation - Yue Wang and Tingmei Hou & Sophia Miranda Garcia - LAS review.pdf\nInternal redline LAS CA Married IPs Wang-Hou - Single SM Sophia Garcia v2 12.03.24.doc...
18,25-S-22,25-S-22 Wenyan Le - Agency Service Agreement Review,agreement file found but wrong format/name,Wenyan Le- Agency Agreement.pdf\nWenyan Le- Cost Estimate .pdf
19,25-S-41,25-S-41 Pei Wang & Elizabeth Hayes - LAS - TERMINATED,case terminated,Agreement for Legal Representation - Pei Wang & Elizabeth Hayes - LAS 01292025.pdf\nAgreement for Legal Representation - Pei Wang & Elizabeth Hayes - LAS.docx\nChinese Agreement for Legal Representation - Pei Wang & Elizabeth Hayes - LAS.docx\nChinese Agreement for Legal Representation - Pei Wan...
20,25-S-142,25-S-142 Nanqi Shi and Linyu Rao & Medinah Wardinski - LAS TERMINATED,case terminated,Agreement for Legal Representation - Nanqi Shi and Linyu Rao & Medinah Wardinski - LAS.docx\nAgreement for Legal Representation - Nanqi Shi and Linyu Rao & Medinah Wardinski - LAS.pdf\nChinese Agreement for Legal Representation - Nanqi Shi and Linyu Rao & Medinah Wardinski - LAS.docx\nChinese Ag...
21,25-S-151,25-S-151 Li and She & Mares (AZ) - SurrogateFirst NMC Break will change the folder later,agreement exists but not marked as signed,Agreement for Legal Representation - Li and She & Mares (AZ) - SurrogateFirst.docx\nAgreement for Legal Representation - Li and She & Mares (AZ) - SurrogateFirst.pdf\nBrittany Match Sheet.pdf\nInvoice 3826.pdf
22,25-S-215,25-S-215 Jihui Yang and Jeffrey Minchieh Hsu & Alisha Scott - LAS Terminated,case terminated,Agreement for Legal Representation -Jihui Yang and Jeffrey Minchieh Hsu & Alisha Scott - LAS.docx\nAgreement for Legal Representation -Jihui Yang and Jeffrey Minchieh Hsu & Alisha Scott - LAS.pdf\nAlisha Scott- Match sheet.pdf\nChinese Agreement for Legal Representation - Jihui Yang and Jeffrey ...
23,25-S-241,25-S-241 Isreb & Knapp PBO review - Surro Connections,agreement exists but not marked as signed,Agreement for Legal Representation - Isreb & Knapp - Surro Connections PBO review.doc\nAgreement for Legal Representation - Isreb & Knapp - Surro Connections PBO review.pdf\nCertified Judgment_Knapp.pdf\nDocuments for Review.pdf\nGC Agreement - Knapp to Isreb - EXECUTION COPY - 04-27-23 rev1 - s...
24,25-S-349,25-S-349 Beroukhai & Hernandez Leon - Smart Surrogacy,agreement exists but not marked as signed,Agreement for Legal Representation - CA.docx\nAgreement for Legal Representation - CA.pdf\nBenefit Package.pdf\nInternal drafting Gestational Surrogacy Agreement - Zhang & Chidester (AZ) - Stronger Together Surrogacy.docx\nMatching Sheet.pdf
25,25-S-377,25-S-377 Zhou and Yang & Arias (TX) - Blossom California Fertility,agreement exists but not marked as signed,Agreement for Legal Representation - Zhou and Yang & Arias (TX) - Blossom California Fertility.docx\nAgreement for Legal Representation - Zhou and Yang & Arias (TX) - Blossom California Fertility.pdf\nChinese Agreement for Legal Representation - Zhou and Yang & Arias (TX) - Blossom California Fe...
26,25-S-412,25-S-412 Her and Lee & Aquino (AZ) - WFI review,agreement exists but not marked as signed,Agreement for Legal Representation - Her and Lee & Aquino (AZ) - WFI.pdf\nAgreement for Legal Representation - Her and Lee & Aquino (AZ).docx\nUpdated Lawyer Match Sheet Jaclyn.pdf\nsigned retainer signature page.pdf
27,25-S-447,25-S-447 Special Parentage - Liu and Gao & Cortes - SAI,agreement exists but not marked as signed,Agreement for Legal Representation - Liu and Gao & Cortes - SAI.docx\nAgreement for Legal Representation - Liu and Gao & Cortes - SAI.pdf\nBirth Certificate.jpeg\nChinese Agreement for Legal Representation- Liu and Gao & Cortes - SAI.docx\nIP Signed GSA.pdf\nMatch Info.pdf\nPBO Info.pdf\nunnamed...
28,25-S-455,25-S-455 Jingyu Ma & Destanee Gonzales - LAS - Terminated,case terminated,Agreement for Legal Representation - Jingyu Ma & Destanee Gonzales - LAS.docx\nAgreement for Legal Representation - Jingyu Ma & Destanee Gonzales - LAS.pdf\nChinese Agreement for Legal Representation- Jingyu Ma & Destanee Gonzales - LAS.docx\nChinese Agreement for Legal Representation- Jingyu Ma...
29,25-S-504,25-S-504 Prieston and Markula & Lipuma-Tweito - Indy (AZ) review,agreement exists but not marked as signed,2nd Redline Surrogacy Agreement Prieston and Markula & Lipuma-Tweito.pdf\nAgreement for Legal Representation - Prieston and Markula & Lipuma-Tweito review.docx\nAgreement for Legal Representation - Prieston and Markula & Lipuma-Tweito review.pdf\nExhibit A - Surrogacy Agreement 12.09.2025 FINAL....
30,25-S-516,25-S-516 Yajin Li and Zihan Jiang & Meriteza Gallardo - LAS - Terminated,case terminated,10 Match Sheet.zdoc_Merged (10).pdf\nAgreement for Legal Representation - Yajin Li and Zihan Jiang & Meriteza Gallardo - LAS.docx\nAgreement for Legal Representation - Yajin Li and Zihan Jiang & Meriteza Gallardo - LAS.pdf\nChinese Agreement for Legal Representation- Yajin Li and Zihan Jiang & M...
31,25-S-522,25-S-522 Zhang & Buenrostro - Flying Stork Surrogacy,agreement exists but not marked as signed,(IP Notarized) FINAL Gestational Surrogacy Agreement - Zhang & Buenrostro - Flying Stork Surrogacy.pdf\nAgreement for Legal Representation - Zhang & Buenrostro - Flying Stork Surrogacy.docx\nAgreement for Legal Representation - Zhang & Buenrostro - Flying Stork Surrogacy.pdf\nChinese Agreement f...
32,25-S-541,25-S-541 Claire Heffernan & Edith Mamie Duyen Massaquoi (PA) - LAS Terminated,case terminated,Agreement for Legal Representation - Claire Heffernan & Edith Mamie Duyen Massaquoi (PA) - LAS.docx\nAgreement for Legal Representation - Claire Heffernan & Edith Mamie Duyen Massaquoi (PA) - LAS.pdf\nEdith D - LAS Benefit Package - Current version Feb 2025.pdf\nEdith Duyen-Massaquoi - 10 Match ...
33,26-S-15,26-S-15 Jihui Yang and Jeffrey Hsu & Isabella Perez (OK) - LAS - Terminated,case terminated,Agreement for Legal Representation - Jihui Yang and Jeffrey Hsu & Isabella Perez (OK) - LAS.docx\nAgreement for Legal Representation - Jihui Yang and Jeffrey Hsu & Isabella Perez (OK) - LAS.pdf\nIsabella P - LAS Benefit Package - Current version Feb 2025.pdf\nIsabella Perez - 10 Match Sheet.zdoc...
34,26-S-91,26-S-91 Nan Feng and Qun Wu & Kylee Johnson (IN) - LAS,agreement exists but not marked as signed,10 Match Sheet_Merged (32).pdf\nAgreement for Legal Representation - Nan Feng and Qun Wu & Kylee Johnson (IN) - LAS.docx\nAgreement for Legal Representation - Nan Feng and Qun Wu & Kylee Johnson (IN) - LAS.pdf\nChinese Agreement for Legal Representation- Nan Feng and Qun Wu & Kylee Johnson (IN) ...
35,26-S-187,26-S-187 Yu & Garcia Jaime - Babies Sprouts review,agreement exists but not marked as signed,"$65,000_Benefit_Package_Paquete_de_Beneficio.pdf\n3b237bb502c1a39807dd525d1de15159.jpg\nAgreement for Legal Representation - Yu & Garcia - Babies Sprouts review.docx\nAgreement for Legal Representation - Yu & Garcia - Babies Sprouts review.pdf\nInvoice 4965.pdf\nJessica_C_Estimated_Cost_Sheet.pd..."
36,26-S-204,26-S-204 Kit Man Grace Hui and Yan Wang & Stephanie Rojas - LAS - Terminated,case terminated,Agreement for Legal Representation - Kit Man Grace Hui and Yan Wang & Stephanie Rojas - LAS.docx\nAgreement for Legal Representation - Kit Man Grace Hui and Yan Wang & Stephanie Rojas - LAS.pdf\nChn Agreement for Legal Representation - Kit Man Grace Hui and Yan Wang & Stephanie Rojas - LAS.docx\...
37,26-S-219,26-S-219 Tingting Zhang & Timsline Charles (FL) - LAS,agreement exists but not marked as signed,(Maria edits) FIRST DRAFT Gestational Surrogacy Agreement - Tingting Zhang Timsline Charles (FL) - LAS.docx\nAgreement for Legal Representation - Tingting Zhang & Timsline Charles (FL) - LAS.docx\nAgreement for Legal Representation - Tingting Zhang & Timsline Charles (FL) - LAS.pdf\nChinese Dra...
38,26-S-239,26-S-239 Junting Zhang & Shelby Nunes - LAS,agreement exists but not marked as signed,(IP Notarized) FINAL Gestational Surrogacy Agreement - Junting Zhang & Shelby Nunes - LAS.pdf\nAgreement for Legal Representation - Junting Zhang & Shelby Nunes - LAS.docx\nAgreement for Legal Representation - Junting Zhang & Shelby Nunes - LAS.pdf\nChinese Agreement for Legal Representation - J...
39,26-S-243,26-S-243 Cirulli and Schneider & Wolfinger - Simple Steps Fertility,agreement exists but not marked as signed,Agreement for Legal Representation - Cirulli and Schneider & Wolfinger - Simple Steps Fertility.docx\nAgreement for Legal Representation - Cirulli and Schneider & Wolfinger - Simple Steps Fertility.pdf\nInternal Drafting GSA - Cirulli and Schneider & Wolfinger - Simple Steps Fertility.docx\nNata...
40,26-S-268,26-S-268 Wu & Santana - Origins Family Surrogacy,agreement exists but not marked as signed,Agreement for Legal Representation - Wu & Santana - Origins Family Surrogacy.docx\nAgreement for Legal Representation - Wu & Santana - Origins Family Surrogacy.pdf\nChinese Agreement for Legal Representation - Wu & Santana - Origins Family Surrogacy.docx\nChinese Agreement for Legal Representati...
41,26-S-278,26-S-278 Krishnan & Hoff – GTS,agreement exists but not marked as signed,Agreement for Legal Representation - Krishnan & Hoff - GTS.docx\nAgreement for Legal Representation - Krishnan & Hoff - GTS.pdf\nEmily Hoff - DL front and SS.jpg\nFinancial Timeline - Emily H.pdf\nGTS Match Sheet - Emily H.pdf\nIF - ID.jpeg\nIM - ID.jpeg\nInternal Drafting Gestational Surrogacy ...
42,26-S-284,26-S-284 Minyu Zhang and Xu Ji & Brianna Villalba Acosta - LAS,agreement exists but not marked as signed,(2IP - 1GC) Internal Drafting GSA - Chung-Hui Liang and Shiou-Yuan Chen & Yolanda Campos - LAS.docx\nAgreement for Legal Representation - Minyu Zhang and Xu Ji & Brianna Villalba Acosta - LAS (2).pdf\nAgreement for Legal Representation - Minyu Zhang and Xu Ji & Brianna Villalba Acosta - LAS.docx...
43,26-S-286,26-S-286 McLay and Bradlyn & Yadgarov (IL) - Compass Family Journeys review,agreement exists but not marked as signed,Agreement for Legal Representation - McLay and Bradlyn & Yadgarov (IL) - Compass Family Journeys review.docx\nAgreement for Legal Representation - McLay and Bradlyn & Yadgarov (IL) - Compass Family Journeys review.pdf\nAlyssa Y Compensation (2).pdf\nAlyssa Yadgarov info.pdf\nAttorney Sheet-Alyss...
44,26-S-287,26-S-287 Cai and Yuan (NY) & Chavez (IL) - Alcea Surrogacy,agreement exists but not marked as signed,"Aaliyah_Compensation Acknowledgement.pdf\nAgreement for Legal Representation - Cai and Yuan (NY) & Chavez (IL) - Alcea Surrogacy.docx\nAgreement for Legal Representation - Cai and Yuan (NY) & Chavez (IL) - Alcea Surrogacy.pdf\nLegal Match Terms_ Yang_Cai_A. Chavez.pdf\nTsong Law Group, APC Mail ..."
45,26-S-288,26-S-288 Travers and Townsend & Blount (AZ) - Newgen Families,agreement exists but not marked as signed,Agreement for Legal Representation - Travers and Townsend & Blount (AZ) - Newgen Families.docx\nAgreement for Legal Representation - Travers and Townsend & Blount (AZ) - Newgen Families.pdf\nKavindra Match sheet.pdf\nmatch info.pdf
46,26-S-289,26-S-289 Liu & Lopez - ACRC,agreement exists but not marked as signed,Agreement for Legal Representation - Liu & Lopez - ACRC.docx\nAgreement for Legal Representation - Liu & Lopez - ACRC.pdf\nChinese Agreement for Legal Representation - Liu & Lopez - ACRC.docx\nChinese Agreement for Legal Representation - Liu & Lopez - ACRC.pdf\nChinese internal drafting Gestatio...
47,26-S-290,26-S-290 Chung & Pallares - C&T Fertility Consultant review,agreement exists but not marked as signed,Agreement for Legal Representation - Chung & Pallares - C&T Fertility Consultant review.docx\nAgreement for Legal Representation - Chung & Pallares - C&T Fertility Consultant review.pdf\nMatch Sheet IP Shih-pin Chung GC kassandra.pdf\nREDLINE FROM GC LAST MATCH.docx\nbenefit package Kassandra ....
48,26-S-291,26-S-291 Tran and Wong & Wallin - Simple Steps Fertility,agreement exists but not marked as signed,Agreement for Legal Representation - Tran and Wong & Wallin - Simple Steps Fertility.docx\nAgreement for Legal Representation - Tran and Wong & Wallin - Simple Steps Fertility.pdf\nEmployer Hours Confirmation_Evelyn Wallin.pdf\nFee Sheet - Tran_Wong_Wallin.pdf\nGC Benefit Package_Evelyn Wallin.p...
49,26-S-292,26-S-292 Partovi & Stevenson (WA) - GTS review,agreement exists but not marked as signed,Agreement for Legal Representation - Partovi & Stevenson (WA) - GTS review.docx\nAgreement for Legal Representation - Partovi & Stevenson (WA) - GTS review.pdf\nBecca_and_Hadi_-_Fees___Expenses_Schedule_(Match_Guaranteed_Program)_(1) (1).pdf\nGiving Tree Match Sheet - Kayla S.pdf\nKayla_Benefits...
50,26-S-293,26-S-293 Hu and Schiffer & Jimenez - Loving Journey,agreement exists but not marked as signed,Agreement for Legal Representation - Hu and Schiffer & Jimenez - Loving Journey.docx\nAgreement for Legal Representation - Hu and Schiffer & Jimenez - Loving Journey.pdf\nChinese Agreement for Legal Representation - Hu and Schiffer & Jimenez - Loving Journey.docx\nChinese Agreement for Legal Rep...
51,26-S-XXX,26-S-XXX Wei Yi and Run Zhang & Brenda Perez - LAS,agreement exists but not marked as signed,Agreement for Legal Representation - Run Zhang and Wei Yi & Brenda Perez - LAS.docx\nAgreement for Legal Representation - Wei Yi and Run Zhang & Brenda Perez - LAS.pdf\nBrenda P - LAS Benefit Package - Current version Feb 2025.docx\nChinese Agreement for Legal Representation - Run Zhang and Wei ...
52,26-S-XXX,26-S-XXX Yingzi Cai and Hao Wen & Kayla Marie Gonzalez - LAS,agreement exists but not marked as signed,Agreement for Legal Representation - Yingzi Cai and Hao Wen & Kayla Marie Gonzalez - LAS.docx\nAgreement for Legal Representation - Yingzi Cai and Hao Wen & Kayla Marie Gonzalez - LAS.pdf\nChinese Agreement for Legal Representation - Yingzi Cai and Hao Wen & Kayla Marie Gonzalez - LAS.docx\nChin...
53,26-S-XXX,26-S-XXX Zhang & Ward - Twinkle Surrogacy,agreement exists but not marked as signed,Agreement for Legal Representation - Zhang & Ward - Twinkle Surrogacy.docx\nAgreement for Legal Representation - Zhang & Ward - Twinkle Surrogacy.pdf\nChinese Agreement for Legal Representation - Zhang & Ward - Twinkle Surrogacy.doc\nChinese Agreement for Legal Representation - Zhang & Ward - Tw...

In [66]:
# ── Export to cases stats folder ───────────────────────────────────────────────

OUT_DIR = r"C:\Users\zhous\OneDrive - Tsong Law Group\Ralph Tsong's files - Marketing\cases stats"
os.makedirs(OUT_DIR, exist_ok=True)

# ── Rebuild summaries ──────────────────────────────────────────────────────────
_pivot_month = (
    df.groupby(['month', 'status'])
      .size().unstack(fill_value=0)
      .reindex(columns=['drafting', 'review'], fill_value=0)
)
_pivot_month['total'] = _pivot_month.sum(axis=1)
_pivot_month.loc['TOTAL'] = _pivot_month.sum()

_pivot_agency = (
    df.groupby(['agency', 'status'])
      .size().unstack(fill_value=0)
      .reindex(columns=['drafting', 'review'], fill_value=0)
)
_pivot_agency['total'] = _pivot_agency.sum(axis=1)
_pivot_agency = _pivot_agency.sort_values('total', ascending=False)

_pivot_agency_month = (
    df.groupby(['agency', 'month'])
      .size().unstack(fill_value=0)
)
_pivot_agency_month['TOTAL'] = _pivot_agency_month.sum(axis=1)
_pivot_agency_month = _pivot_agency_month.sort_values('TOTAL', ascending=False)

_all_cases = df[['month', 'date', 'agency', 'status', 'source', 'case_folder', 'agreement_file']].copy()
_all_cases.index = range(1, len(_all_cases) + 1)
_all_cases.index.name = '#'

# ── HTML style ─────────────────────────────────────────────────────────────────
_CSS = """
<style>
  body { font-family: Arial, sans-serif; font-size: 13px; margin: 20px; }
  h2   { color: #2c3e50; }
  table { border-collapse: collapse; width: 100%; }
  th   { background: #2c3e50; color: white; padding: 6px 10px; text-align: left; }
  td   { padding: 5px 10px; border-bottom: 1px solid #ddd; white-space: pre-wrap; }
  tr:nth-child(even) { background: #f5f5f5; }
</style>
"""

def _to_html(title, frame):
    return f"<html><head><meta charset='utf-8'>{_CSS}</head><body><h2>{title}</h2>{frame.to_html()}</body></html>"

# ── Write files ────────────────────────────────────────────────────────────────
exports = {
    'all_cases':             (_all_cases,           'All Cases (1 row per case)'),
    'monthly_summary':       (_pivot_month,          'Monthly Summary'),
    'agency_summary':        (_pivot_agency,         'Agency Summary'),
    'agency_x_month':        (_pivot_agency_month,   'Agency × Month Breakdown'),
    'missing_cases':         (miss_df,               'Missing Cases (no agreement / clearance letter)'),
}

for fname, (frame, title) in exports.items():
    csv_path  = os.path.join(OUT_DIR, f'{fname}.csv')
    html_path = os.path.join(OUT_DIR, f'{fname}.html')
    frame.to_csv(csv_path, encoding='utf-8-sig')
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(_to_html(title, frame))
    print(f'✓  {fname}.csv  +  {fname}.html')

print(f'\nSaved to: {OUT_DIR}')

✓  all_cases.csv  +  all_cases.html
✓  monthly_summary.csv  +  monthly_summary.html
✓  agency_summary.csv  +  agency_summary.html
✓  agency_x_month.csv  +  agency_x_month.html
✓  missing_cases.csv  +  missing_cases.html

Saved to: C:\Users\zhous\OneDrive - Tsong Law Group\Ralph Tsong's files - Marketing\cases stats

In [67]:
# ── Interactive charts — setup ─────────────────────────────────────────────────
%pip install -q plotly
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

OUT_DIR = r"C:\Users\zhous\OneDrive - Tsong Law Group\Ralph Tsong's files - Marketing\cases stats"
_COLORS = {'drafting': '#2c7bb6', 'review': '#d7191c'}

# ── 1. Monthly case volume ─────────────────────────────────────────────────────
_m = (df.groupby(['month', 'status']).size().unstack(fill_value=0)
        .reindex(columns=['drafting', 'review'], fill_value=0))
_m['total'] = _m.sum(axis=1)

fig1 = go.Figure()
fig1.add_bar(x=_m.index, y=_m['drafting'], name='Drafting',
             marker_color=_COLORS['drafting'],
             text=_m['drafting'], textposition='inside')
fig1.add_bar(x=_m.index, y=_m['review'], name='Review',
             marker_color=_COLORS['review'],
             text=_m['review'], textposition='inside')
fig1.add_scatter(x=_m.index, y=_m['total'], name='Total',
                 mode='lines+markers', line=dict(color='#333', width=2),
                 marker=dict(size=6))
fig1.update_layout(
    title='Monthly Case Volume',
    barmode='stack', xaxis_title='Month', yaxis_title='Cases',
    hovermode='x unified', template='plotly_white',
    legend=dict(orientation='h', y=1.08)
)
fig1.show()

Note: you may need to restart the kernel to use updated packages.

In [68]:
# ── 2. Top 30 agencies — pie chart ────────────────────────────────────────────
_a = (df.groupby(['agency', 'status']).size().unstack(fill_value=0)
        .reindex(columns=['drafting', 'review'], fill_value=0))
_a['total'] = _a.sum(axis=1)
_a = _a.sort_values('total', ascending=False).head(30)

fig2 = go.Figure(go.Pie(
    labels=_a.index,
    values=_a['total'],
    textinfo='label+percent+value',
    hovertemplate='%{label}<br>Cases: %{value}<br>%{percent}<extra></extra>',
))
fig2.update_layout(
    title='Top 30 Agencies by Case Count',
    template='plotly_white',
    height=800,
)
fig2.show()

In [69]:
# ── 3. Agency × Month heatmap (top 30 agencies) ───────────────────────────────
_h = (df.groupby(['agency', 'month']).size().unstack(fill_value=0))
_h['_total'] = _h.sum(axis=1)
_h = _h.sort_values('_total', ascending=False).head(30).drop(columns='_total')

fig3 = go.Figure(go.Heatmap(
    z=_h.values,
    x=_h.columns.tolist(),
    y=_h.index.tolist(),
    colorscale='Blues',
    text=_h.values,
    texttemplate='%{text}',
    hovertemplate='Agency: %{y}<br>Month: %{x}<br>Cases: %{z}<extra></extra>',
))
fig3.update_layout(
    title='Agency × Month Heatmap (Top 30 Agencies)',
    xaxis_title='Month', yaxis_title='',
    template='plotly_white', height=800,
    xaxis=dict(tickangle=-45)
)
fig3.show()

In [70]:
# ── 4. Cumulative cases over time ─────────────────────────────────────────────
_cum = _m[['drafting', 'review', 'total']].cumsum()

fig4 = go.Figure()
fig4.add_scatter(x=_cum.index, y=_cum['total'], name='Total',
                 fill='tozeroy', line=dict(color='#555', width=2))
fig4.add_scatter(x=_cum.index, y=_cum['drafting'], name='Drafting',
                 line=dict(color=_COLORS['drafting'], width=2, dash='dot'))
fig4.add_scatter(x=_cum.index, y=_cum['review'], name='Review',
                 line=dict(color=_COLORS['review'], width=2, dash='dot'))
fig4.update_layout(
    title='Cumulative Cases Over Time',
    xaxis_title='Month', yaxis_title='Cumulative Cases',
    template='plotly_white', hovermode='x unified',
    legend=dict(orientation='h', y=1.08)
)
fig4.show()

In [71]:
# ── 5. Source breakdown — donut ───────────────────────────────────────────────
_src = df['source'].value_counts()
fig5 = go.Figure(go.Pie(
    labels=_src.index, values=_src.values,
    hole=0.45,
    marker_colors=['#2c7bb6', '#abd9e9'],
    textinfo='label+percent+value',
))
fig5.update_layout(
    title='Cases by Source (Signed Agreement vs Clearance Letter)',
    template='plotly_white'
)
fig5.show()

In [72]:
# ── 6. Agency time series — drafting vs review by month (interactive dropdown) ─

# Monthly counts per agency + status
_ts = (
    df.groupby(['agency', 'month', 'status'])
      .size()
      .unstack(fill_value=0)
      .reindex(columns=['drafting', 'review'], fill_value=0)
      .reset_index()
)

# Agencies sorted by total cases descending (most active first in dropdown)
_agency_order = df.groupby('agency').size().sort_values(ascending=False).index.tolist()

fig6 = go.Figure()

# Two traces per agency (drafting + review); only the first agency is visible
for i, agency in enumerate(_agency_order):
    ag = _ts[_ts['agency'] == agency].sort_values('month')
    vis = (i == 0)
    fig6.add_scatter(
        x=ag['month'], y=ag['drafting'],
        name='Drafting', mode='lines+markers',
        line=dict(color=_COLORS['drafting'], width=2),
        marker=dict(size=7), visible=vis,
        hovertemplate='%{x}<br>Drafting: %{y}<extra></extra>',
    )
    fig6.add_scatter(
        x=ag['month'], y=ag['review'],
        name='Review', mode='lines+markers',
        line=dict(color=_COLORS['review'], width=2),
        marker=dict(size=7), visible=vis,
        hovertemplate='%{x}<br>Review: %{y}<extra></extra>',
    )

# Dropdown: each button shows only 2 traces for the selected agency
n = len(_agency_order)
_buttons = []
for i, agency in enumerate(_agency_order):
    vis_list = [False] * (2 * n)
    vis_list[2 * i]     = True  # drafting
    vis_list[2 * i + 1] = True  # review
    _buttons.append(dict(
        label=agency,
        method='update',
        args=[
            {'visible': vis_list},
            {'title': f'Monthly Cases Over Time — {agency}'},
        ],
    ))

fig6.update_layout(
    title=f'Monthly Cases Over Time — {_agency_order[0]}',
    xaxis_title='Month',
    yaxis_title='Cases',
    template='plotly_white',
    height=520,
    hovermode='x unified',
    legend=dict(orientation='h', y=1.14),
    updatemenus=[dict(
        buttons=_buttons,
        direction='down',
        showactive=True,
        x=0.0,
        xanchor='left',
        y=1.25,
        yanchor='top',
        bgcolor='white',
        bordercolor='#ccc',
    )],
)
fig6.show()

In [73]:
# ── Save all charts to cases stats folder ────────────────────────────────────
charts = {
    'chart_monthly_volume':    fig1,
    'chart_top_agencies':      fig2,
    'chart_agency_heatmap':    fig3,
    'chart_cumulative':        fig4,
    'chart_source_breakdown':  fig5,
    'chart_agency_timeseries': fig6,
}

for fname, fig in charts.items():
    fig.write_html(f'{OUT_DIR}\\{fname}.html', include_plotlyjs='cdn')
    print(f'✓  {fname}.html')

print(f'\nSaved to: {OUT_DIR}')

✓  chart_monthly_volume.html
✓  chart_top_agencies.html
✓  chart_agency_heatmap.html
✓  chart_cumulative.html
✓  chart_source_breakdown.html
✓  chart_agency_timeseries.html

Saved to: C:\Users\zhous\OneDrive - Tsong Law Group\Ralph Tsong's files - Marketing\cases stats